import type { BootstrapData } from '../types';

function setWidths(sheet:any,widths:number[]){sheet['!cols']=widths.map(w=>({wch:w}))}
function append(XLSX:any,wb:any,name:string,rows:any[],widths:number[]){const ws=rows.length?XLSX.utils.json_to_sheet(rows):XLSX.utils.aoa_to_sheet([['Sem registros']]);setWidths(ws,widths);XLSX.utils.book_append_sheet(wb,ws,name)}

export async function exportYvieWorkbook(data:BootstrapData){
  const XLSX=await import('xlsx');const wb=XLSX.utils.book_new();wb.Props={Title:'YVIE Gestão',Subject:'Exportação completa do ERP YVIE',Author:'YVIE'};
  const summary=[['YVIE — Resumo gerencial',''],['Indicador','Valor'],['Faturamento',data.summary.revenue],['Lucro bruto',data.summary.grossProfit],['Despesas pagas',data.summary.expenses],['Lucro líquido',data.summary.netProfit],['Lucro retido',data.summary.retainedProfit],['Retirada sugerida',data.summary.suggestedWithdrawal],['Aportes',data.summary.ownerContributions],['Pró-labore',data.summary.ownerPayroll],['Retiradas',data.summary.ownerWithdrawals],['Créditos de clientes em aberto',data.summary.customerCreditOutstanding],['A receber',data.summary.receivablePending],['Despesas a pagar',data.summary.payableExpenses],['Pedidos',data.summary.orders],['Ticket médio',data.summary.ticketAverage],['Peças em estoque',data.summary.stockUnits],['Capital investido no estoque',data.summary.stockCost],['Posição de capital operacional',data.summary.workingCapitalPosition],['Faturamento potencial do estoque',data.summary.stockPotentialRevenue],['Lucro bruto potencial do estoque',data.summary.stockPotentialProfit],['Compras pendentes',data.summary.pendingPurchases],['Exportado em',new Date().toLocaleString('pt-BR')]];
  const wsSummary=XLSX.utils.aoa_to_sheet(summary);setWidths(wsSummary,[38,22]);XLSX.utils.book_append_sheet(wb,wsSummary,'Resumo');

  append(XLSX,wb,'Estoque',data.products.flatMap(p=>p.variants.filter(v=>v.active).map(v=>({Produto:p.name,Categoria:p.category,Coleção:p.collection||'',Cor:v.color||'',Tamanho:v.size||'',SKU:v.sku||'',Quantidade:v.stock,'Custo médio':v.averageCost,'Preço à vista':v.cashPrice,'Preço cartão':v.cardPrice,'Capital investido':v.stock*v.averageCost,'Faturamento potencial':v.stock*v.cashPrice,'Lucro potencial':v.stock*(v.cashPrice-v.averageCost)}))),[26,18,16,16,12,18,12,14,14,14,18,20,18]);
  append(XLSX,wb,'Movimentações',data.movements.map(m=>({Data:m.createdAt,Produto:m.productName,Cor:m.color||'',Tamanho:m.size||'',Tipo:m.type,Quantidade:m.quantity,'Custo unitário':m.unitCost??'',Referência:m.note||m.referenceId||''})),[22,26,15,12,16,12,16,35]);
  append(XLSX,wb,'Vendas e pedidos',data.sales.map(s=>({Pedido:s.number,Data:s.createdAt,Cliente:s.customerName,Telefone:s.customerPhone,'Status do pedido':s.orderStatus,'Entregue em':s.deliveredAt||'','Forma entrega':s.deliveryMethod||'',Endereço:s.deliveryAddress||'','Data prometida':s.promisedDate||'',Observações:s.orderNotes||'','Status pagamento':s.paymentStatus,'Forma de pagamento':s.paymentMethod,Subtotal:s.subtotal,Desconto:s.discount,'Crédito usado':s.creditUsed,'Valor do pedido':s.total,'Valor a pagar':s.amountDue,Custo:s.costTotal,Lucro:s.profit})),[16,22,28,18,18,22,16,35,16,35,18,20,14,12,14,14,14,14,14]);
  append(XLSX,wb,'Itens de vendas',data.sales.flatMap(s=>s.items.map(i=>({Pedido:s.number,Cliente:s.customerName,Produto:i.productName,Cor:i.color||'',Tamanho:i.size||'',Quantidade:i.quantity,'Preço unitário':i.unitPrice,'Custo unitário':i.unitCost,'Total vendido':i.quantity*i.unitPrice,'Lucro do item':i.quantity*(i.unitPrice-i.unitCost)}))),[16,26,26,15,12,12,16,16,16,16]);
  append(XLSX,wb,'A receber',data.receivables.map(r=>({Pedido:r.saleNumber,Cliente:r.customerName,Descrição:r.description,Valor:r.amount,Vencimento:r.dueDate||'',Status:r.status,'Recebido em':r.receivedAt||'',Criado:r.createdAt})),[16,26,30,14,14,14,22,22]);
  append(XLSX,wb,'Trocas e devoluções',data.returns.map(r=>({Registro:r.number,Pedido:r.saleNumber,Cliente:r.customerName,Tipo:r.type,Reembolso:r.refundAmount,Crédito:r.creditAmount,Observações:r.notes||'',Data:r.createdAt})),[18,16,26,14,14,14,35,22]);
  append(XLSX,wb,'Itens devoluções',data.returns.flatMap(r=>r.items.map(i=>({Registro:r.number,Pedido:r.saleNumber,Produto:i.productName,Cor:i.color||'',Tamanho:i.size||'',Direção:i.direction,Quantidade:i.quantity,'Preço unitário':i.unitPrice,'Custo unitário':i.unitCost}))),[18,16,26,15,12,12,12,16,16]);
  append(XLSX,wb,'Créditos clientes',data.customerCredits.map(c=>({Data:c.createdAt,Cliente:c.customerName,Pedido:c.saleNumber||'',Tipo:c.type,Valor:c.amount,Observação:c.note||''})),[22,28,18,14,14,40]);
  append(XLSX,wb,'Despesas',data.expenses.map(e=>({Data:e.expenseDate,Descrição:e.description,Beneficiário:e.beneficiary||'',Categoria:e.category,Valor:e.amount,Status:e.status,Vencimento:e.dueDate||'','Pago em':e.paidAt||'',Recorrente:e.recurring?'Sim':'Não',Observações:e.notes||''})),[14,30,24,20,14,14,14,22,12,35]);
  append(XLSX,wb,'Clientes',data.customers.map(c=>({Nome:c.name,Telefone:c.phone,Instagram:c.instagram||'','E-mail':c.email||'',Cidade:c.city||'','Crédito disponível':c.creditBalance,Tags:c.tags.join(', '),Observações:c.notes||'',Cadastro:c.createdAt})),[28,18,20,30,18,18,24,38,22]);
  append(XLSX,wb,'Fornecedores',data.suppliers.map(s=>({Nome:s.name,Telefone:s.phone||'',Instagram:s.instagram||'','E-mail':s.email||'',CNPJ:s.cnpj||'',Status:s.active?'Ativo':'Arquivado',Observações:s.notes||''})),[30,18,20,30,20,14,38]);
  append(XLSX,wb,'Compras',data.purchases.map(p=>({Compra:p.number,Data:p.purchaseDate,Fornecedor:p.supplierName,Status:p.status,Unidades:p.totalUnits,Mercadorias:p.itemsSubtotal,Frete:p.freightCost,'Outros custos':p.otherCost,'Custo total':p.totalCost,'Recebido em':p.receivedAt||'',Observações:p.notes||''})),[20,14,28,14,12,14,12,14,14,22,35]);
  append(XLSX,wb,'Itens de compras',data.purchases.flatMap(p=>p.items.map(i=>({Compra:p.number,Fornecedor:p.supplierName,Produto:i.productName,Cor:i.color||'',Tamanho:i.size||'',SKU:i.sku||'',Quantidade:i.quantity,'Custo unitário':i.unitCost,Subtotal:i.quantity*i.unitCost}))),[20,28,26,15,12,18,12,16,14]);
  append(XLSX,wb,'Precificação',data.pricing.map(r=>({Data:r.createdAt,Produto:r.productName,Cor:r.color||'',Tamanho:r.size||'','Custo da peça':r.pieceCost,Frete:r.freightCost,'Outros custos':r.otherCost,'Custo total':r.totalCost,'Margem alvo %':r.targetMargin,'Taxa cartão %':r.cardFee,'Preço à vista':r.cashPrice,'Preço cartão':r.cardPrice})),[22,26,15,12,16,12,14,14,16,16,16,16]);
  append(XLSX,wb,'Inventários',data.inventoryCounts.map(c=>({Contagem:c.title,Status:c.status,Criado:c.createdAt,'Aplicado em':c.appliedAt||'',Itens:c.items.length,Divergências:c.items.filter(i=>i.difference!==0).length,'Diferença absoluta':c.items.reduce((a,i)=>a+Math.abs(i.difference),0),Observações:c.notes||''})),[28,14,22,22,10,14,18,35]);
  append(XLSX,wb,'Capital e retiradas',data.ownerTransactions.map(o=>({Data:o.transactionDate,Tipo:o.type,Valor:o.amount,Observações:o.notes||'',Criado:o.createdAt})),[14,18,16,40,22]);

  const date=new Date().toISOString().slice(0,10);XLSX.writeFile(wb,`YVIE_Gestao_${date}.xlsx`,{compression:true});
}
