import { integer, makeId, now, number } from '../db';
import { fail, json, readJson } from '../http';
import type { Env } from '../types';

type ReturnPayload={type?:'Devolução'|'Troca';returnedItems?:Array<{saleItemId?:string;quantity?:number}>;exchangeItems?:Array<{productId?:string;variantId?:string;quantity?:number;unitPrice?:number}>;refundAmount?:number;creditAmount?:number;additionalPaymentStatus?:'Pago'|'Pendente';notes?:string;};
const isCardMethod=(method:string)=>['Débito','Crédito'].includes(method);

export async function createReturn(request:Request,env:Env,saleId:string){
  const input=await readJson<ReturnPayload>(request);const sale=await env.DB.prepare(`SELECT * FROM sales WHERE id=? AND deleted_at IS NULL`).bind(saleId).first<any>();if(!sale)return fail('Venda não encontrada.',404);if(sale.order_status==='Cancelado')return fail('Não é possível devolver itens de uma venda cancelada.',409);
  const returned=Array.isArray(input.returnedItems)?input.returnedItems:[];const exchange=Array.isArray(input.exchangeItems)?input.exchangeItems:[];if(!returned.length)return fail('Selecione ao menos um item que está retornando.');
  const pendingRows=await env.DB.prepare(`SELECT * FROM accounts_receivable WHERE sale_id=? AND status='Pendente' ORDER BY COALESCE(due_date,substr(created_at,1,10)),created_at`).bind(saleId).all<any>();const pendingReceivables=pendingRows.results||[];const pendingTotal=pendingReceivables.reduce((sum:any,row:any)=>sum+Number(row.amount||0),0);
  const revisionRow=await env.DB.prepare(`SELECT COUNT(*) n FROM returns WHERE sale_id=?`).bind(saleId).first<any>();const settlementRevision=Number(revisionRow?.n||0);
  if(sale.payment_status==='Pendente'&&pendingTotal<=0.009)return fail('Este pedido está marcado como pendente, mas não possui uma conta a receber ativa. Corrija o financeiro antes de registrar a devolução.',409);
  if(sale.payment_status==='Pago'&&pendingTotal>0.009)return fail('Este pedido está marcado como pago, mas ainda possui conta a receber pendente. Corrija o financeiro antes de registrar a devolução.',409);

  const returnId=makeId('ret');const timestamp=now();const numberCode=`TR-${Date.now().toString().slice(-8)}`;const statements:D1PreparedStatement[]=[env.DB.prepare(`INSERT INTO operation_guards(operation_key,created_at) VALUES(?,?)`).bind(`return-settlement:${saleId}:${settlementRevision}`,timestamp)];let returnedValue=0;
  const discountFactor=Number(sale.subtotal)>0?Math.max(0,Math.min(1,Number(sale.total)/Number(sale.subtotal))):1;
  for(const raw of returned){
    const item=await env.DB.prepare(`SELECT si.*,p.name AS product_name FROM sale_items si JOIN products p ON p.id=si.product_id WHERE si.id=? AND si.sale_id=?`).bind(String(raw.saleItemId||''),saleId).first<any>();if(!item)return fail('Um dos itens não pertence a essa venda.',409);
    const quantity=integer(raw.quantity);if(quantity<1)return fail('Quantidade devolvida inválida.');const already=Number(item.returned_quantity||0);if(quantity+already>Number(item.quantity))return fail(`A quantidade devolvida de ${item.product_name} ultrapassa o que ainda pode ser devolvido.`,409);
    const unitCost=Math.max(0,Number(item.unit_cost||0));const returnUnitPrice=Math.max(0,Number(item.unit_price||0)*discountFactor);returnedValue+=quantity*returnUnitPrice;
    statements.push(env.DB.prepare(`UPDATE sale_items SET returned_quantity=returned_quantity+? WHERE id=?`).bind(quantity,item.id));
    statements.push(env.DB.prepare(`UPDATE product_variants SET average_cost=CASE WHEN stock+?>0 THEN ((stock*average_cost)+(?*?))/(stock+?) ELSE ? END,stock=stock+?,updated_at=? WHERE id=?`).bind(quantity,quantity,unitCost,quantity,unitCost,quantity,timestamp,item.variant_id));
    statements.push(env.DB.prepare(`INSERT INTO return_items(id,return_id,sale_item_id,product_id,variant_id,quantity,direction,unit_cost,unit_price) VALUES(?,?,?,?,?,?,?,?,?)`).bind(makeId('rti'),returnId,item.id,item.product_id,item.variant_id,quantity,'Entrada',unitCost,returnUnitPrice));
    statements.push(env.DB.prepare(`INSERT INTO inventory_movements(id,product_id,variant_id,type,quantity,unit_cost,reference_type,reference_id,note,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(makeId('mov'),item.product_id,item.variant_id,'Devolução',quantity,unitCost,'return',returnId,`${input.type==='Troca'?'Troca':'Devolução'} ${sale.number}`,timestamp));
  }

  let exchangeValue=0;
  for(const raw of exchange){const variant=await env.DB.prepare(`SELECT v.*,p.name AS product_name,p.status AS product_status FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.id=? AND v.product_id=?`).bind(String(raw.variantId||''),String(raw.productId||'')).first<any>();if(!variant||!variant.active||variant.product_status!=='Ativo')return fail('Uma das peças de troca não está disponível.',409);const quantity=integer(raw.quantity);if(quantity<1||Number(variant.stock)<quantity)return fail(`Estoque insuficiente para ${variant.product_name}.`,409);const cashPrice=Math.max(0,number(variant.cash_price,number(variant.sale_price)));const cardPrice=Math.max(0,number(variant.card_price,cashPrice));const automaticPrice=isCardMethod(String(sale.payment_method||''))?cardPrice:cashPrice;const unitPrice=Math.max(0,number(raw.unitPrice,automaticPrice));exchangeValue+=quantity*unitPrice;statements.push(env.DB.prepare(`UPDATE product_variants SET stock=stock-?,updated_at=? WHERE id=?`).bind(quantity,timestamp,variant.id));statements.push(env.DB.prepare(`INSERT INTO return_items(id,return_id,sale_item_id,product_id,variant_id,quantity,direction,unit_cost,unit_price) VALUES(?,?,?,?,?,?,?,?,?)`).bind(makeId('rti'),returnId,null,variant.product_id,variant.id,quantity,'Saída',variant.average_cost,unitPrice));statements.push(env.DB.prepare(`INSERT INTO inventory_movements(id,product_id,variant_id,type,quantity,unit_cost,reference_type,reference_id,note,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(makeId('mov'),variant.product_id,variant.id,'Venda',-quantity,variant.average_cost,'return',returnId,`Saída em troca ${sale.number}`,timestamp));}

  const customerFavor=Math.max(0,returnedValue-exchangeValue);const additional=Math.max(0,exchangeValue-returnedValue);const debtOffset=Math.min(customerFavor,pendingTotal);const settlementAvailable=Math.max(0,customerFavor-debtOffset);const refund=Math.max(0,number(input.refundAmount,settlementAvailable));const credit=Math.max(0,number(input.creditAmount,0));if(Math.abs((refund+credit)-settlementAvailable)>0.009)return fail('Defina todo o valor restante entre reembolso e crédito da cliente.',409);const additionalStatus=additional>0?(input.additionalPaymentStatus==='Pendente'?'Pendente':'Pago'):null;
  statements.push(env.DB.prepare(`INSERT INTO returns(id,number,sale_id,type,refund_amount,credit_amount,returned_value,exchange_value,debt_offset,additional_amount,additional_payment_status,notes,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(returnId,numberCode,saleId,input.type==='Troca'?'Troca':'Devolução',refund,credit,returnedValue,exchangeValue,debtOffset,additional,additionalStatus,typeof input.notes==='string'&&input.notes.trim()?input.notes.trim():null,timestamp));
  const receivableMustChange=debtOffset>0.009||(additional>0.009&&additionalStatus==='Pendente');if(receivableMustChange){const newPending=Math.max(0,pendingTotal-debtOffset+(additionalStatus==='Pendente'?additional:0));for(const row of pendingReceivables)statements.push(env.DB.prepare(`UPDATE accounts_receivable SET status='Cancelado',updated_at=? WHERE id=? AND status='Pendente'`).bind(timestamp,row.id));if(newPending>0.009){const dueDate=pendingReceivables.find((r:any)=>r.due_date)?.due_date||timestamp.slice(0,10);statements.push(env.DB.prepare(`INSERT INTO accounts_receivable(id,sale_id,description,amount,due_date,status,created_at,updated_at) VALUES(?,?,?,?,?,'Pendente',?,?)`).bind(makeId('rec'),saleId,`Saldo após ${numberCode}`,newPending,dueDate,timestamp,timestamp));statements.push(env.DB.prepare(`UPDATE sales SET payment_status='Pendente',updated_at=? WHERE id=?`).bind(timestamp,saleId));}else statements.push(env.DB.prepare(`UPDATE sales SET payment_status='Pago',updated_at=? WHERE id=?`).bind(timestamp,saleId));}
  if(credit>0)statements.push(env.DB.prepare(`INSERT INTO customer_credit_movements(id,customer_id,sale_id,return_id,type,amount,note,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(makeId('ccm'),sale.customer_id,saleId,returnId,'Crédito',credit,`Crédito gerado por ${numberCode}`,timestamp));
  await env.DB.batch(statements);return json({id:returnId,number:numberCode,returnedValue,exchangeValue,debtOffset,additionalAmount:additional,additionalPaymentStatus:additionalStatus,refundAmount:refund,creditAmount:credit},201);
}
