import { BanknoteArrowDown, CircleDollarSign, Landmark, Plus, Trash2, WalletCards } from 'lucide-react';
import { useState } from 'react';
import { Badge, Button, ConfirmDialog, Drawer, EmptyState, Field, Input, PageHeader, Select, StatCard, Textarea } from '../components/ui';
import { useData } from '../context/DataContext';
import { api, notify } from '../lib/api';
import { money, shortDate } from '../lib/format';
import type { OwnerTransaction } from '../types';

const blank=()=>({type:'Pró-labore' as OwnerTransaction['type'],amount:0,transactionDate:new Date().toISOString().slice(0,10),notes:''});
export function Capital(){
  const {data,refresh}=useData();const [open,setOpen]=useState(false);const [form,setForm]=useState(blank());const [busy,setBusy]=useState(false);const [del,setDel]=useState<OwnerTransaction|null>(null);
  if(!data)return null;const s=data.summary;
  async function save(){if(form.amount<=0)return;setBusy(true);try{await api('/api/owner-transactions',{method:'POST',body:JSON.stringify(form)});setOpen(false);setForm(blank());await refresh();notify('Movimentação de capital registrada.')}finally{setBusy(false)}}
  async function remove(){if(!del)return;setBusy(true);try{await api(`/api/owner-transactions/${del.id}`,{method:'DELETE'});setDel(null);await refresh();notify('Movimentação removida.')}finally{setBusy(false)}}
  return <>
    <PageHeader title="Capital e retiradas" subtitle="Separe patrimônio da empresa, lucro retido, pró-labore e retiradas sem confundir estoque com dinheiro disponível." actions={<Button variant="primary" onClick={()=>{setForm(blank());setOpen(true)}}><Plus size={16}/>Registrar movimentação</Button>}/>
    <div className="stats-grid four"><StatCard label="Capital no estoque" value={money(s.stockCost)} note={`${s.stockUnits} peças ainda imobilizadas`} icon={<WalletCards size={17}/>}/><StatCard label="Lucro líquido acumulado" value={money(s.netProfit)} note="Antes de pró-labore e retiradas" icon={<CircleDollarSign size={17}/>}/><StatCard label="Lucro retido" value={money(s.retainedProfit)} note="Lucro menos pró-labore e retiradas" icon={<Landmark size={17}/>}/><StatCard label="Retirada sugerida" value={money(s.suggestedWithdrawal)} note="Estimativa após compromissos e créditos de clientes" icon={<BanknoteArrowDown size={17}/>}/></div>
    <div className="finance-position-grid"><article><div><Landmark size={17}/><span>Aportes</span></div><strong>{money(s.ownerContributions)}</strong><small>Capital colocado pelos sócios</small></article><article><div><BanknoteArrowDown size={17}/><span>Pró-labore</span></div><strong>{money(s.ownerPayroll)}</strong><small>Remuneração já retirada</small></article><article><div><BanknoteArrowDown size={17}/><span>Outras retiradas</span></div><strong>{money(s.ownerWithdrawals)}</strong><small>Distribuições e retiradas registradas</small></article><article><div><WalletCards size={17}/><span>Posição operacional</span></div><strong>{money(s.workingCapitalPosition)}</strong><small>Estoque + a receber + aportes − obrigações e retiradas</small></article></div>
    <div className="stock-projection-note"><strong>Quanto posso tirar?</strong><span>A “retirada sugerida” é gerencial: parte do lucro líquido acumulado, desconta o que já foi retirado, despesas pendentes e créditos que a empresa deve às clientes. Ela não substitui o saldo do banco nem cálculo fiscal de pró-labore.</span></div>
    <section className="table-panel">{data.ownerTransactions.length?<div className="table-scroll"><table><thead><tr><th>Data</th><th>Tipo</th><th>Valor</th><th>Observação</th><th></th></tr></thead><tbody>{data.ownerTransactions.map(t=><tr key={t.id}><td>{shortDate(t.transactionDate)}</td><td><Badge tone={t.type==='Aporte'?'success':t.type==='Pró-labore'?'info':'warning'}>{t.type}</Badge></td><td><strong>{money(t.amount)}</strong></td><td>{t.notes||'—'}</td><td><button className="icon-btn danger-icon" title="Excluir movimentação" onClick={()=>setDel(t)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>:<EmptyState icon={<Landmark/>} title="Nenhuma movimentação dos sócios" text="Registre aportes, pró-labore e retiradas para separar capital da empresa do dinheiro pessoal."/>}</section>
    <Drawer open={open} title="Movimentação de capital" subtitle="Aporte aumenta o capital dos sócios; pró-labore e retirada reduzem o lucro ainda não retirado." onClose={()=>setOpen(false)} footer={<><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="primary" loading={busy} disabled={form.amount<=0} onClick={()=>void save()}>Salvar</Button></>}><div className="form-grid one-col"><Field label="Tipo"><Select value={form.type} onChange={e=>setForm({...form,type:e.target.value as OwnerTransaction['type']})}><option>Aporte</option><option>Pró-labore</option><option>Retirada</option></Select></Field><Field label="Valor"><Input type="number" min="0" step=".01" value={form.amount||''} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></Field><Field label="Data"><Input type="date" value={form.transactionDate} onChange={e=>setForm({...form,transactionDate:e.target.value})}/></Field><Field label="Observação"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Ex.: pró-labore de agosto"/></Field></div></Drawer>
    <ConfirmDialog open={!!del} title="Excluir movimentação?" text="O valor deixará de compor os indicadores de capital e retiradas." onClose={()=>setDel(null)} onConfirm={remove} busy={busy}/>
  </>;
}
