import { BadgeDollarSign, MessageCircle, Pencil, Plus, Trash2, UserRound, Users } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useData } from '../context/DataContext';
import { api, notify } from '../lib/api';
import { dateTime, money, phoneDisplay, shortDate, whatsAppUrl } from '../lib/format';
import type { Customer } from '../types';
import { Badge, Button, ConfirmDialog, Drawer, EmptyState, Field, Input, PageHeader, SearchInput, Select, Textarea } from '../components/ui';

const blank={name:'',phone:'',instagram:'',email:'',city:'',tags:'',notes:''};
export function Customers(){
  const {data,refresh}=useData(); const [q,setQ]=useState(''); const [editing,setEditing]=useState<Customer|null>(null); const [open,setOpen]=useState(false); const [form,setForm]=useState(blank); const [busy,setBusy]=useState(false); const [del,setDel]=useState<Customer|null>(null);const [creditCustomer,setCreditCustomer]=useState<Customer|null>(null);const [creditMode,setCreditMode]=useState<'add'|'remove'>('add');const [creditAmount,setCreditAmount]=useState(0);const [creditNote,setCreditNote]=useState('');
  const rows=useMemo(()=>data?.customers.filter(c=>`${c.name} ${c.phone} ${c.instagram||''} ${c.city||''}`.toLowerCase().includes(q.toLowerCase()))||[],[data,q]);
  function create(){setEditing(null);setForm(blank);setOpen(true)}
  function edit(c:Customer){setEditing(c);setForm({name:c.name,phone:c.phone,instagram:c.instagram||'',email:c.email||'',city:c.city||'',tags:c.tags.join(', '),notes:c.notes||''});setOpen(true)}
  function openCredit(c:Customer){setCreditCustomer(c);setCreditMode('add');setCreditAmount(0);setCreditNote('')}
  async function save(){if(!form.name.trim()||!form.phone.trim())return;setBusy(true);try{const body={...form,tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean)};await api(editing?`/api/customers/${editing.id}`:'/api/customers',{method:editing?'PUT':'POST',body:JSON.stringify(body)});setOpen(false);await refresh()}finally{setBusy(false)}}
  async function saveCredit(){if(!creditCustomer||creditAmount<=0)return;const signed=creditMode==='add'?creditAmount:-creditAmount;setBusy(true);try{await api(`/api/customers/${creditCustomer.id}/credit`,{method:'POST',body:JSON.stringify({amount:signed,note:creditNote||`${creditMode==='add'?'Crédito':'Baixa de crédito'} manual`})});await refresh();setCreditCustomer(null);notify('Saldo de crédito atualizado.')}finally{setBusy(false)}}
  async function remove(){if(!del)return;setBusy(true);try{await api(`/api/customers/${del.id}`,{method:'DELETE'});setDel(null);await refresh()}finally{setBusy(false)}}
  return <>
    <PageHeader title="Clientes" subtitle="Histórico de relacionamento, compras, crédito disponível e acesso rápido ao WhatsApp." actions={<Button variant="primary" onClick={create}><Plus size={16}/>Novo cliente</Button>}/>
    <div className="toolbar"><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, telefone ou Instagram..."/></div>
    <section className="table-panel">{rows.length?<div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Contato</th><th>Cidade</th><th>Pedidos</th><th>Total comprado</th><th>Crédito</th><th>Última compra</th><th>Tags</th><th></th></tr></thead><tbody>{rows.map(c=>{const sales=data?.sales.filter(s=>s.customerId===c.id&&s.orderStatus!=='Cancelado')||[];const total=sales.reduce((a,s)=>a+s.total,0);return <tr key={c.id}><td><div className="entity"><div className="entity-icon"><UserRound size={16}/></div><div><strong>{c.name}</strong><span>{c.instagram||'Sem Instagram'}</span></div></div></td><td>{phoneDisplay(c.phone)}</td><td>{c.city||'—'}</td><td>{sales.length}</td><td>{money(total)}</td><td className={c.creditBalance>0?'positive':''}><strong>{money(c.creditBalance)}</strong></td><td>{sales[0]?shortDate(sales[0].createdAt):'—'}</td><td>{c.tags.length?<div className="tag-row">{c.tags.slice(0,2).map(t=><Badge key={t}>{t}</Badge>)}</div>:'—'}</td><td><div className="row-actions"><a className="icon-btn" href={whatsAppUrl(c.phone)} target="_blank" rel="noreferrer" title="Abrir WhatsApp"><MessageCircle size={15}/></a><button className="icon-btn" onClick={()=>openCredit(c)} title="Crédito da cliente"><BadgeDollarSign size={15}/></button><button className="icon-btn" onClick={()=>edit(c)} title="Editar"><Pencil size={15}/></button><button className="icon-btn danger-icon" onClick={()=>setDel(c)} title="Excluir"><Trash2 size={15}/></button></div></td></tr>})}</tbody></table></div>:<EmptyState icon={<Users/>} title="Nenhum cliente encontrado" text="Cadastre clientes para construir um histórico de relacionamento." action={<Button onClick={create}>Cadastrar cliente</Button>}/>}</section>
    <Drawer open={open} title={editing?'Editar cliente':'Novo cliente'} subtitle="Os dados ficam disponíveis em vendas e no histórico." onClose={()=>setOpen(false)} footer={<><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="primary" loading={busy} onClick={save}>Salvar cliente</Button></>}><div className="form-grid"><Field label="Nome" required className="span-2"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome completo"/></Field><Field label="WhatsApp" required helper="Será usado no botão wa.me"><Input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="(81) 99999-9999"/></Field><Field label="Instagram"><Input value={form.instagram} onChange={e=>setForm({...form,instagram:e.target.value})} placeholder="@usuario"/></Field><Field label="E-mail"><Input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Cidade"><Input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></Field><Field label="Tags" className="span-2" helper="Separe por vírgula"><Input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="VIP, recorrente"/></Field><Field label="Observações" className="span-2"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div></Drawer>
    <Drawer open={!!creditCustomer} title="Crédito da cliente" subtitle={creditCustomer?`${creditCustomer.name} · saldo atual ${money(creditCustomer.creditBalance)}`:''} onClose={()=>setCreditCustomer(null)} footer={<><Button onClick={()=>setCreditCustomer(null)}>Fechar</Button><Button variant="primary" loading={busy} disabled={creditAmount<=0||(creditMode==='remove'&&creditAmount>(creditCustomer?.creditBalance||0))} onClick={()=>void saveCredit()}>Registrar ajuste</Button></>}>
      {creditCustomer&&<><div className="summary-box"><div><span>Saldo disponível</span><strong>{money(creditCustomer.creditBalance)}</strong></div><div><span>Após ajuste</span><strong>{money(Math.max(0,creditCustomer.creditBalance+(creditMode==='add'?creditAmount:-creditAmount)))}</strong></div></div><div className="form-grid one-col"><Field label="Operação"><Select value={creditMode} onChange={e=>setCreditMode(e.target.value as 'add'|'remove')}><option value="add">Adicionar crédito</option><option value="remove">Baixar / corrigir crédito</option></Select></Field><Field label="Valor"><Input type="number" min="0" step=".01" value={creditAmount||''} onChange={e=>setCreditAmount(Math.max(0,Number(e.target.value)))}/></Field><Field label="Motivo"><Textarea value={creditNote} onChange={e=>setCreditNote(e.target.value)} placeholder="Ex.: ajuste autorizado, crédito promocional..."/></Field></div><div className="section-divider"/><div className="section-title-row"><div><h3>Histórico de crédito</h3><p>Devoluções, usos, estornos e ajustes manuais.</p></div></div><div className="credit-ledger">{data?.customerCredits.filter(x=>x.customerId===creditCustomer.id).length?data.customerCredits.filter(x=>x.customerId===creditCustomer.id).map(x=><div key={x.id}><div><strong>{x.type}</strong><span>{x.note||x.saleNumber||'Movimentação'} · {dateTime(x.createdAt)}</span></div><b className={x.amount>=0?'positive':'negative'}>{x.amount>=0?'+ ':''}{money(x.amount)}</b></div>):<p className="muted-cell">Nenhuma movimentação de crédito.</p>}</div></>}
    </Drawer>
    <ConfirmDialog open={!!del} title="Excluir cliente?" text="Só é permitido excluir clientes sem vendas, crédito ou outros registros vinculados." onClose={()=>setDel(null)} onConfirm={remove} busy={busy}/>
  </>
}
