import { MessageCircle, Pencil, Plus, Trash2, UserRound, Users } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useData } from '../context/DataContext';
import { api } from '../lib/api';
import { money, phoneDisplay, shortDate, whatsAppUrl } from '../lib/format';
import type { Customer } from '../types';
import { Badge, Button, ConfirmDialog, Drawer, EmptyState, Field, Input, PageHeader, SearchInput, Textarea } from '../components/ui';

const blank={name:'',phone:'',instagram:'',email:'',city:'',tags:'',notes:''};
export function Customers(){
  const {data,refresh}=useData(); const [q,setQ]=useState(''); const [editing,setEditing]=useState<Customer|null>(null); const [open,setOpen]=useState(false); const [form,setForm]=useState(blank); const [busy,setBusy]=useState(false); const [del,setDel]=useState<Customer|null>(null);
  const rows=useMemo(()=>data?.customers.filter(c=>`${c.name} ${c.phone} ${c.instagram||''} ${c.city||''}`.toLowerCase().includes(q.toLowerCase()))||[],[data,q]);
  function create(){setEditing(null);setForm(blank);setOpen(true)}
  function edit(c:Customer){setEditing(c);setForm({name:c.name,phone:c.phone,instagram:c.instagram||'',email:c.email||'',city:c.city||'',tags:c.tags.join(', '),notes:c.notes||''});setOpen(true)}
  async function save(){if(!form.name.trim()||!form.phone.trim())return;setBusy(true);try{const body={...form,tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean)};await api(editing?`/api/customers/${editing.id}`:'/api/customers',{method:editing?'PUT':'POST',body:JSON.stringify(body)});setOpen(false);await refresh()}finally{setBusy(false)}}
  async function remove(){if(!del)return;setBusy(true);try{await api(`/api/customers/${del.id}`,{method:'DELETE'});setDel(null);await refresh()}finally{setBusy(false)}}
  return <>
    <PageHeader title="Clientes" subtitle="Histórico de relacionamento, compras e acesso rápido ao WhatsApp." actions={<Button variant="primary" onClick={create}><Plus size={16}/>Novo cliente</Button>}/>
    <div className="toolbar"><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, telefone ou Instagram..."/></div>
    <section className="table-panel">{rows.length?<div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Contato</th><th>Cidade</th><th>Pedidos</th><th>Total comprado</th><th>Última compra</th><th>Tags</th><th></th></tr></thead><tbody>{rows.map(c=>{const sales=data?.sales.filter(s=>s.customerId===c.id&&s.orderStatus!=='Cancelado')||[];const total=sales.reduce((a,s)=>a+s.total,0);return <tr key={c.id}><td><div className="entity"><div className="entity-icon"><UserRound size={16}/></div><div><strong>{c.name}</strong><span>{c.instagram||'Sem Instagram'}</span></div></div></td><td>{phoneDisplay(c.phone)}</td><td>{c.city||'—'}</td><td>{sales.length}</td><td>{money(total)}</td><td>{sales[0]?shortDate(sales[0].createdAt):'—'}</td><td>{c.tags.length?<div className="tag-row">{c.tags.slice(0,2).map(t=><Badge key={t}>{t}</Badge>)}</div>:'—'}</td><td><div className="row-actions"><a className="icon-btn" href={whatsAppUrl(c.phone)} target="_blank" rel="noreferrer" title="Abrir WhatsApp"><MessageCircle size={15}/></a><button className="icon-btn" onClick={()=>edit(c)} title="Editar"><Pencil size={15}/></button><button className="icon-btn danger-icon" onClick={()=>setDel(c)} title="Excluir"><Trash2 size={15}/></button></div></td></tr>})}</tbody></table></div>:<EmptyState icon={<Users/>} title="Nenhum cliente encontrado" text="Cadastre clientes para construir um histórico de relacionamento." action={<Button onClick={create}>Cadastrar cliente</Button>}/>}</section>
    <Drawer open={open} title={editing?'Editar cliente':'Novo cliente'} subtitle="Os dados ficam disponíveis em vendas e no histórico." onClose={()=>setOpen(false)} footer={<><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="primary" loading={busy} onClick={save}>Salvar cliente</Button></>}><div className="form-grid"><Field label="Nome" required className="span-2"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome completo"/></Field><Field label="WhatsApp" required helper="Será usado no botão wa.me"><Input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="(81) 99999-9999"/></Field><Field label="Instagram"><Input value={form.instagram} onChange={e=>setForm({...form,instagram:e.target.value})} placeholder="@usuario"/></Field><Field label="E-mail"><Input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Cidade"><Input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></Field><Field label="Tags" className="span-2" helper="Separe por vírgula"><Input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="VIP, recorrente"/></Field><Field label="Observações" className="span-2"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div></Drawer>
    <ConfirmDialog open={!!del} title="Excluir cliente?" text="Só é permitido excluir clientes sem vendas vinculadas." onClose={()=>setDel(null)} onConfirm={remove} busy={busy}/>
  </>
}
