import { CheckCircle2, Pencil, Plus, Receipt, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Badge, Button, ConfirmDialog, Drawer, EmptyState, Field, Input, PageHeader, SearchInput, Select, StatCard, Textarea } from '../components/ui';
import { useData } from '../context/DataContext';
import { api, notify } from '../lib/api';
import { money, shortDate } from '../lib/format';
import type { Expense } from '../types';

const blank=()=>({description:'',category:'',amount:0,expenseDate:new Date().toISOString().slice(0,10),recurring:'false',status:'Pago',dueDate:'',beneficiary:'',notes:''});
export function Expenses(){
  const {data,refresh}=useData();const [q,setQ]=useState('');const [status,setStatus]=useState('');const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Expense|null>(null);const [form,setForm]=useState(blank());const [busy,setBusy]=useState(false);const [remove,setRemove]=useState<Expense|null>(null);
  const rows=useMemo(()=>data?.expenses.filter(e=>(!status||e.status===status)&&`${e.description} ${e.category} ${e.beneficiary||''}`.toLowerCase().includes(q.toLowerCase()))||[],[data,q,status]);
  const paid=data?.expenses.filter(e=>e.status==='Pago').reduce((a,e)=>a+e.amount,0)||0;const pending=data?.expenses.filter(e=>e.status==='Pendente').reduce((a,e)=>a+e.amount,0)||0;
  function create(){setEditing(null);setForm(blank());setOpen(true)}
  function edit(e:Expense){setEditing(e);setForm({description:e.description,category:e.category,amount:e.amount,expenseDate:e.expenseDate,recurring:String(e.recurring),status:e.status,dueDate:e.dueDate||'',beneficiary:e.beneficiary||'',notes:e.notes||''});setOpen(true)}
  async function save(){if(!form.description.trim()||form.amount<=0)return;setBusy(true);try{await api(editing?`/api/expenses/${editing.id}`:'/api/expenses',{method:editing?'PUT':'POST',body:JSON.stringify({...form,recurring:form.recurring==='true'})});setOpen(false);await refresh();notify(`Despesa ${editing?'atualizada':'cadastrada'} com sucesso.`)}finally{setBusy(false)}}
  async function markPaid(e:Expense){setBusy(true);try{await api(`/api/expenses/${e.id}/paid`,{method:'POST'});await refresh();notify('Despesa marcada como paga.')}finally{setBusy(false)}}
  async function doRemove(){if(!remove)return;setBusy(true);try{await api(`/api/expenses/${remove.id}`,{method:'DELETE'});setRemove(null);await refresh();notify('Despesa excluída.')}finally{setBusy(false)}}
  return <>
    <PageHeader title="Despesas" subtitle="Gastos pagos e a pagar, separados do faturamento e das compras de estoque." actions={<Button variant="primary" onClick={create}><Plus size={16}/>Nova despesa</Button>}/>
    <div className="stats-grid four"><StatCard label="Despesas pagas" value={money(paid)} note="Entram no lucro líquido realizado" icon={<Receipt size={17}/>}/><StatCard label="A pagar" value={money(pending)} note="Compromissos ainda pendentes" icon={<Receipt size={17}/>}/><StatCard label="Lançamentos" value={`${data?.expenses.length||0}`} note="Histórico total" icon={<Receipt size={17}/>}/><StatCard label="Recorrentes" value={`${data?.expenses.filter(e=>e.recurring).length||0}`} note="Marcadas como recorrentes" icon={<Receipt size={17}/>}/></div>
    <div className="toolbar toolbar-split"><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar descrição, categoria ou beneficiário..."/><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas</option><option>Pago</option><option>Pendente</option></Select></div>
    <section className="table-panel">{rows.length?<div className="table-scroll"><table><thead><tr><th>Despesa</th><th>Beneficiário</th><th>Categoria</th><th>Data</th><th>Vencimento</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td><strong>{e.description}</strong>{e.recurring&&<span className="cell-sub">recorrente</span>}</td><td>{e.beneficiary||'—'}</td><td>{e.category}</td><td>{shortDate(e.expenseDate)}</td><td>{e.dueDate?shortDate(e.dueDate):'—'}</td><td><strong>{money(e.amount)}</strong></td><td><Badge tone={e.status==='Pago'?'success':'warning'}>{e.status}</Badge></td><td><div className="row-actions">{e.status==='Pendente'&&<button className="icon-btn" title="Marcar como paga" onClick={()=>void markPaid(e)}><CheckCircle2 size={15}/></button>}<button className="icon-btn" title="Editar" onClick={()=>edit(e)}><Pencil size={15}/></button><button className="icon-btn danger-icon" title="Excluir" onClick={()=>setRemove(e)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>:<EmptyState icon={<Receipt/>} title="Nenhuma despesa" text="Cadastre gastos operacionais para acompanhar o resultado real." action={<Button onClick={create}>Cadastrar despesa</Button>}/>}</section>
    <Drawer open={open} title={editing?'Editar despesa':'Nova despesa'} subtitle="Despesas pagas afetam o lucro líquido; pendentes aparecem em contas a pagar." onClose={()=>setOpen(false)} footer={<><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="primary" loading={busy} onClick={save}>Salvar despesa</Button></>}><div className="form-grid"><Field label="Descrição" required className="span-2"><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Beneficiário"><Input value={form.beneficiary} onChange={e=>setForm({...form,beneficiary:e.target.value})} placeholder="Empresa ou pessoa"/></Field><Field label="Categoria"><Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Marketing, embalagem..."/></Field><Field label="Valor" required><Input type="number" min="0" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></Field><Field label="Status"><Select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Pago</option><option>Pendente</option></Select></Field><Field label="Data do lançamento"><Input type="date" value={form.expenseDate} onChange={e=>setForm({...form,expenseDate:e.target.value})}/></Field><Field label="Vencimento"><Input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></Field><Field label="Tipo"><Select value={form.recurring} onChange={e=>setForm({...form,recurring:e.target.value})}><option value="false">Pontual</option><option value="true">Recorrente</option></Select></Field><Field label="Observações" className="span-2"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div></Drawer>
    <ConfirmDialog open={!!remove} title="Excluir despesa?" text={remove?`${remove.description} · ${money(remove.amount)}`:''} onClose={()=>setRemove(null)} onConfirm={doRemove} busy={busy}/>
  </>;
}
