import { Boxes, CircleDollarSign, Clock3, Receipt, ShoppingCart, WalletCards } from 'lucide-react';
import { useMemo, useState } from 'react';
import { PeriodFilter, currentMonthRange, inRange } from '../components/PeriodFilter';
import { useData } from '../context/DataContext';
import { money, shortDate } from '../lib/format';
import { Badge, EmptyState, PageHeader, StatCard } from '../components/ui';

export function Finance(){
  const {data}=useData();const [range,setRange]=useState(currentMonthRange());
  const period=useMemo(()=>{if(!data)return null;const sales=data.sales.filter(s=>s.orderStatus!=='Cancelado'&&inRange(s.createdAt,range));const returns=data.returns.filter(r=>inRange(r.createdAt,range));const revenue=sales.reduce((a,s)=>a+s.total,0)-returns.reduce((a,r)=>a+r.refundAmount+r.creditAmount,0);const saleCost=sales.reduce((a,s)=>a+s.costTotal,0);const returnedCost=returns.flatMap(r=>r.items).filter(i=>i.direction==='Entrada').reduce((a,i)=>a+i.quantity*i.unitCost,0);const exchangeCost=returns.flatMap(r=>r.items).filter(i=>i.direction==='Saída').reduce((a,i)=>a+i.quantity*i.unitCost,0);const cost=saleCost-returnedCost+exchangeCost;const expenses=data.expenses.filter(e=>e.status==='Pago'&&inRange(e.expenseDate,range)).reduce((a,e)=>a+e.amount,0);return{revenue,cost,gross:revenue-cost,expenses,net:revenue-cost-expenses}},[data,range]);
  if(!data||!period)return null;const s=data.summary;
  return <>
    <PageHeader title="Financeiro" subtitle="Resultado realizado, caixa a receber, compromissos e capital imobilizado." actions={<PeriodFilter value={range} onChange={setRange}/>}/>
    <div className="stats-grid four"><StatCard label="Faturamento" value={money(period.revenue)} note={range.label} icon={<WalletCards size={17}/>}/><StatCard label="Lucro bruto" value={money(period.gross)} note="Após custo e devoluções" icon={<CircleDollarSign size={17}/>}/><StatCard label="Despesas pagas" value={money(period.expenses)} note="No período selecionado" icon={<Receipt size={17}/>}/><StatCard label="Lucro líquido" value={money(period.net)} note="Resultado realizado" icon={<CircleDollarSign size={17}/>}/></div>
    <div className="finance-position-grid"><article><div><Boxes size={17}/><span>Capital no estoque</span></div><strong>{money(s.stockCost)}</strong><small>{s.stockUnits} peças disponíveis</small></article><article><div><Clock3 size={17}/><span>A receber</span></div><strong>{money(s.receivablePending)}</strong><small>Vendas ainda não recebidas</small></article><article><div><Receipt size={17}/><span>Despesas a pagar</span></div><strong>{money(s.payableExpenses)}</strong><small>Compromissos pendentes</small></article><article><div><ShoppingCart size={17}/><span>Compras pendentes</span></div><strong>{money(s.pendingPurchases)}</strong><small>Ainda não incorporadas ao estoque</small></article></div>
    <div className="finance-grid"><section className="panel"><div className="panel-head"><div><h2>Próximos recebimentos</h2><p>Vendas pendentes de confirmação financeira.</p></div></div>{data.receivables.filter(r=>r.status==='Pendente').length?<div className="activity-list">{data.receivables.filter(r=>r.status==='Pendente').slice(0,8).map(r=><div className="activity-row" key={r.id}><div className="activity-mark"><Clock3 size={15}/></div><div className="activity-main"><strong>{r.customerName}</strong><span>{r.saleNumber} · {r.dueDate?`vence ${shortDate(r.dueDate)}`:'sem vencimento'}</span></div><div className="activity-side"><strong>{money(r.amount)}</strong><Badge tone="warning">Pendente</Badge></div></div>)}</div>:<EmptyState icon={<Clock3/>} title="Nada a receber" text="Vendas pendentes aparecerão automaticamente aqui."/>}</section><section className="panel"><div className="panel-head"><div><h2>Composição do período</h2><p>Separada do valor que ainda está parado no estoque.</p></div></div><div className="result-sheet"><div><span>Faturamento líquido</span><strong>{money(period.revenue)}</strong></div><div><span>(−) Custo das peças</span><strong>{money(period.cost)}</strong></div><div><span>Lucro bruto</span><strong>{money(period.gross)}</strong></div><div><span>(−) Despesas pagas</span><strong>{money(period.expenses)}</strong></div><div className="result-total"><span>Lucro líquido</span><strong>{money(period.net)}</strong></div></div></section></div>
  </>
}
