import { Boxes, CircleDollarSign, Plus, Receipt, ShoppingCart, Trash2, WalletCards } from 'lucide-react';
import { useState } from 'react';
import { useData } from '../context/DataContext';
import { api, notify } from '../lib/api';
import { money, shortDate } from '../lib/format';
import { Button, Drawer, EmptyState, Field, Input, PageHeader, Select, StatCard, Textarea } from '../components/ui';

export function Finance(){
 const {data,refresh}=useData();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [form,setForm]=useState({description:'',category:'',amount:0,expenseDate:new Date().toISOString().slice(0,10),recurring:'false',notes:''});if(!data)return null;const s=data.summary;
 async function save(){if(!form.description||form.amount<=0)return;setBusy(true);try{await api('/api/expenses',{method:'POST',body:JSON.stringify({...form,recurring:form.recurring==='true'})});setOpen(false);setForm({...form,description:'',category:'',amount:0,notes:''});await refresh();notify('Despesa registrada e considerada no lucro líquido.')}finally{setBusy(false)}}
 async function remove(id:string){await api(`/api/expenses/${id}`,{method:'DELETE'});await refresh();notify('Despesa removida.')}
 return <>
  <PageHeader title="Financeiro" subtitle="Resultado realizado, despesas, capital imobilizado e compromissos de compra." actions={<Button variant="primary" onClick={()=>setOpen(true)}><Plus size={16}/>Nova despesa</Button>}/>
  <div className="stats-grid four"><StatCard label="Faturamento" value={money(s.revenue)} note="Receita de vendas" icon={<WalletCards size={17}/>}/><StatCard label="Custo das mercadorias" value={money(s.revenue-s.grossProfit)} note="Custo das peças já vendidas" icon={<Receipt size={17}/>}/><StatCard label="Despesas" value={money(s.expenses)} note="Gastos operacionais cadastrados" icon={<Receipt size={17}/>}/><StatCard label="Lucro líquido" value={money(s.netProfit)} note="Resultado após custos e despesas" icon={<CircleDollarSign size={17}/>}/></div>
  <div className="finance-position-grid"><article><div><Boxes size={17}/><span>Capital no estoque</span></div><strong>{money(s.stockCost)}</strong><small>{s.stockUnits} peças ainda disponíveis</small></article><article><div><CircleDollarSign size={17}/><span>Venda potencial do estoque</span></div><strong>{money(s.stockPotentialRevenue)}</strong><small>Com os preços atuais/precificados</small></article><article><div><WalletCards size={17}/><span>Lucro potencial do estoque</span></div><strong>{money(s.stockPotentialProfit)}</strong><small>Antes de novas despesas</small></article><article><div><ShoppingCart size={17}/><span>Compras a receber</span></div><strong>{money(s.pendingPurchases)}</strong><small>Pedidos ainda não incorporados ao estoque</small></article></div>
  <div className="finance-grid"><section className="panel"><div className="panel-head"><div><h2>Despesas</h2><p>Lançamentos operacionais que reduzem o lucro líquido.</p></div></div>{data.expenses.length?<div className="activity-list">{data.expenses.map(e=><div className="activity-row" key={e.id}><div className="activity-mark"><Receipt size={15}/></div><div className="activity-main"><strong>{e.description}</strong><span>{e.category} · {shortDate(e.expenseDate)}{e.recurring?' · recorrente':''}</span></div><div className="activity-side"><strong>{money(e.amount)}</strong><button className="icon-btn danger-icon" title="Excluir despesa" onClick={()=>void remove(e.id)}><Trash2 size={14}/></button></div></div>)}</div>:<EmptyState icon={<Receipt/>} title="Sem despesas" text="Cadastre gastos para acompanhar o lucro líquido."/>}</section><section className="panel"><div className="panel-head"><div><h2>Composição do resultado</h2><p>O que já aconteceu nas vendas, sem misturar estoque ainda não vendido.</p></div></div><div className="result-sheet"><div><span>Faturamento</span><strong>{money(s.revenue)}</strong></div><div><span>(−) Custo das peças vendidas</span><strong>{money(s.revenue-s.grossProfit)}</strong></div><div><span>Lucro bruto</span><strong>{money(s.grossProfit)}</strong></div><div><span>(−) Despesas</span><strong>{money(s.expenses)}</strong></div><div className="result-total"><span>Lucro líquido</span><strong>{money(s.netProfit)}</strong></div></div></section></div>
  <Drawer open={open} title="Nova despesa" subtitle="Cadastre gastos operacionais para que o lucro líquido não fique artificialmente inflado." onClose={()=>setOpen(false)} footer={<><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="primary" loading={busy} onClick={save}>Salvar despesa</Button></>}><div className="form-grid"><Field label="Descrição" required className="span-2"><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Categoria"><Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Marketing, embalagem..."/></Field><Field label="Valor" required><Input type="number" min="0" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></Field><Field label="Data"><Input type="date" value={form.expenseDate} onChange={e=>setForm({...form,expenseDate:e.target.value})}/></Field><Field label="Tipo"><Select value={form.recurring} onChange={e=>setForm({...form,recurring:e.target.value})}><option value="false">Pontual</option><option value="true">Recorrente</option></Select></Field><Field label="Observações" className="span-2"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div></Drawer>
 </>
}
