import { FileSpreadsheet, Upload } from 'lucide-react';
import { useState } from 'react';
import { Button, EmptyState, PageHeader } from '../components/ui';
import { useData } from '../context/DataContext';
import { api, notify } from '../lib/api';

type Preview={file:string;customers:any[];stock:any[];expenses:any[];suppliers:any[]};
const txt=(v:any)=>String(v??'').trim();const num=(v:any)=>Number.isFinite(Number(v))?Number(v):0;
export function ImportData(){
  const {data,refresh}=useData();const [preview,setPreview]=useState<Preview|null>(null);const [busy,setBusy]=useState(false);const [progress,setProgress]=useState('');
  async function read(file:File){const XLSX=await import('xlsx');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const json=(name:string)=>wb.Sheets[name]?XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:''}) as any[]:[];setPreview({file:file.name,customers:json('Clientes'),stock:json('Estoque'),expenses:json('Despesas'),suppliers:json('Fornecedores')})}
  async function run(){if(!preview)return;setBusy(true);let done=0,skipped=0;try{
    for(const row of preview.customers){const name=txt(row['Nome']),phone=txt(row['Telefone']).replace(/\D/g,'');if(!name||!phone){skipped++;continue}if(data?.customers.some(c=>c.name.toLowerCase()===name.toLowerCase()&&c.phone.replace(/\D/g,'')===phone)){skipped++;continue}setProgress(`Importando cliente ${name}...`);await api('/api/customers',{method:'POST',body:JSON.stringify({name,phone,instagram:txt(row['Instagram']),email:txt(row['E-mail']),city:txt(row['Cidade']),tags:txt(row['Tags']).split(',').map((x:string)=>x.trim()).filter(Boolean),notes:txt(row['Observações'])})});done++}
    for(const row of preview.suppliers){const name=txt(row['Nome']);if(!name){skipped++;continue}if(data?.suppliers.some(s=>s.name.toLowerCase()===name.toLowerCase())){skipped++;continue}setProgress(`Importando fornecedor ${name}...`);await api('/api/suppliers',{method:'POST',body:JSON.stringify({name,phone:txt(row['Telefone']),instagram:txt(row['Instagram']),email:txt(row['E-mail']),cnpj:txt(row['CNPJ']),notes:txt(row['Observações']),active:txt(row['Status']).toLowerCase()!=='arquivado'})});done++}
    const groups=new Map<string,any[]>();for(const row of preview.stock){const name=txt(row['Produto']);if(!name)continue;if(!groups.has(name))groups.set(name,[]);groups.get(name)!.push(row)}
    for(const [name,rows] of groups){if(data?.products.some(p=>p.name.toLowerCase()===name.toLowerCase())){skipped+=rows.length;continue}setProgress(`Importando produto ${name}...`);const first=rows[0];await api('/api/products',{method:'POST',body:JSON.stringify({name,category:txt(first['Categoria'])||'Sem categoria',collection:txt(first['Coleção']),status:'Ativo',variants:rows.map(r=>({color:txt(r['Cor']),size:txt(r['Tamanho']),sku:txt(r['SKU']),stock:Math.max(0,Math.trunc(num(r['Quantidade']))),minStock:1,averageCost:Math.max(0,num(r['Custo médio'])),salePrice:Math.max(0,num(r['Preço de venda'])),active:true}))})});done+=rows.length}
    for(const row of preview.expenses){const description=txt(row['Descrição']),amount=num(row['Valor']);if(!description||amount<=0){skipped++;continue}setProgress(`Importando despesa ${description}...`);await api('/api/expenses',{method:'POST',body:JSON.stringify({description,category:txt(row['Categoria'])||'Outros',amount,expenseDate:txt(row['Data'])||new Date().toISOString().slice(0,10),recurring:txt(row['Recorrente']).toLowerCase()==='sim',status:txt(row['Status'])==='Pendente'?'Pendente':'Pago',dueDate:txt(row['Vencimento']),beneficiary:txt(row['Beneficiário']),notes:txt(row['Observações'])})});done++}
    await refresh();notify(`Importação concluída: ${done} registros incluídos e ${skipped} ignorados.`);setPreview(null);setProgress('');
  }finally{setBusy(false)}}
  return <><PageHeader title="Importar dados" subtitle="Traga clientes, estoque, despesas e fornecedores de uma planilha Excel sem recadastrar tudo manualmente."/>
    <section className="import-panel"><div className="import-drop"><FileSpreadsheet size={34}/><h2>Selecione uma planilha .xlsx</h2><p>Se for uma exportação do próprio YVIE, as abas Clientes, Estoque, Despesas e Fornecedores serão reconhecidas automaticamente.</p><label className="btn btn-primary import-file"><Upload size={16}/>Escolher arquivo<input type="file" accept=".xlsx,.xls" onChange={e=>{const file=e.target.files?.[0];if(file)void read(file);e.currentTarget.value=''}}/></label></div>{preview&&<div className="import-preview"><div><strong>{preview.file}</strong><span>Revise o que foi encontrado antes de importar.</span></div><div className="import-counts"><article><span>Clientes</span><strong>{preview.customers.length}</strong></article><article><span>Linhas de estoque</span><strong>{preview.stock.length}</strong></article><article><span>Despesas</span><strong>{preview.expenses.length}</strong></article><article><span>Fornecedores</span><strong>{preview.suppliers.length}</strong></article></div><div className="stock-projection-note"><strong>Proteção contra duplicidade</strong><span>Clientes com mesmo nome+telefone, fornecedores com mesmo nome e produtos já existentes são ignorados. A importação não sobrescreve cadastros existentes.</span></div>{progress&&<p className="import-progress">{progress}</p>}<Button variant="primary" loading={busy} onClick={()=>void run()}>Importar registros</Button></div>}{!preview&&<EmptyState icon={<Upload/>} title="Nenhum arquivo selecionado" text="Use preferencialmente uma planilha exportada pelo próprio ERP ou mantenha os mesmos nomes de colunas."/>}</section>
  </>;
}
