import { Boxes, CircleDollarSign, PackageSearch, SlidersHorizontal, TrendingUp, WalletCards } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useData } from '../context/DataContext';
import { api } from '../lib/api';
import { money } from '../lib/format';
import type { Product, Variant } from '../types';
import { Badge, Button, Drawer, EmptyState, Field, Input, PageHeader, SearchInput, Select, StatCard, Textarea } from '../components/ui';

export function Inventory({onNewEntry}:{onNewEntry:()=>void}){
  const {data,refresh}=useData();const [q,setQ]=useState('');const [filter,setFilter]=useState('all');const [selected,setSelected]=useState<{p:Product;v:Variant}|null>(null);const [qty,setQty]=useState(0);const [reason,setReason]=useState('Contagem de estoque');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);
  const rows=useMemo(()=>{const out:( {p:Product;v:Variant})[]=[];data?.products.forEach(p=>p.variants.filter(v=>v.active).forEach(v=>out.push({p,v})));return out.filter(({p,v})=>{const t=`${p.name} ${p.category} ${v.color||''} ${v.size||''} ${v.sku||''}`.toLowerCase();const ok=filter==='low'?v.stock<=v.minStock:filter==='zero'?v.stock===0:true;return ok&&t.includes(q.toLowerCase())})},[data,q,filter]);
  function openAdjust(p:Product,v:Variant){setSelected({p,v});setQty(v.stock);setReason('Contagem de estoque');setNote('')}
  async function adjust(){if(!selected)return;setBusy(true);try{await api(`/api/inventory/${selected.v.id}/adjust`,{method:'POST',body:JSON.stringify({quantity:qty,reason,note})});setSelected(null);await refresh()}finally{setBusy(false)}}
  const s=data?.summary;
  const potentialMargin=s?.stockPotentialRevenue?((s.stockPotentialProfit/s.stockPotentialRevenue)*100):0;
  return <>
    <PageHeader title="Estoque" subtitle="Disponibilidade real por variante, capital investido e potencial de resultado." actions={<Button variant="primary" onClick={onNewEntry}><Boxes size={16}/>Nova entrada</Button>}/>
    {s&&<><div className="stats-grid four inventory-money-grid"><StatCard label="Capital investido" value={money(s.stockCost)} note="Custo médio das peças disponíveis" icon={<WalletCards size={17}/>}/><StatCard label="Faturamento potencial" value={money(s.stockPotentialRevenue)} note="Se todo estoque vender pelo preço atual" icon={<CircleDollarSign size={17}/>}/><StatCard label="Lucro bruto potencial" value={money(s.stockPotentialProfit)} note={`${potentialMargin.toFixed(1)}% de margem potencial`} icon={<TrendingUp size={17}/>}/><StatCard label="Peças disponíveis" value={`${s.stockUnits} un.`} note="Somatório das variantes ativas" icon={<Boxes size={17}/>}/></div><div className="stock-projection-note"><strong>Como é calculado</strong><span>Capital investido = estoque × custo médio. Faturamento potencial = estoque × preço de venda atual/precificado. Lucro potencial = faturamento potencial − capital investido.</span></div></>}
    <div className="toolbar toolbar-split"><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar produto, cor, tamanho ou SKU..."/><Select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todo o estoque</option><option value="low">Estoque baixo</option><option value="zero">Sem estoque</option></Select></div>
    <section className="table-panel">{rows.length?<div className="table-scroll"><table><thead><tr><th>Produto</th><th>Cor</th><th>Tamanho</th><th>SKU</th><th>Quantidade</th><th>Custo médio</th><th>Venda</th><th>Investido</th><th>Lucro potencial</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(({p,v})=><tr key={v.id}><td><div className="entity"><div className="entity-icon">{v.imageUrl||p.imageUrl?<img className="entity-image" src={v.imageUrl||p.imageUrl||''} alt=""/>:<PackageSearch size={16}/>}</div><div><strong>{p.name}</strong><span>{p.category}</span></div></div></td><td>{v.color||'—'}</td><td>{v.size||'—'}</td><td className="muted-cell">{v.sku||'—'}</td><td><strong>{v.stock}</strong> un.</td><td>{money(v.averageCost)}</td><td>{money(v.salePrice)}</td><td>{money(v.stock*v.averageCost)}</td><td className="positive">{money(v.stock*Math.max(0,v.salePrice-v.averageCost))}</td><td><Badge tone={v.stock===0?'danger':v.stock<=v.minStock?'warning':'success'}>{v.stock===0?'Sem estoque':v.stock<=v.minStock?'Baixo':'Disponível'}</Badge></td><td><button className="icon-btn" onClick={()=>openAdjust(p,v)} title="Ajustar estoque"><SlidersHorizontal size={15}/></button></td></tr>)}</tbody></table></div>:<EmptyState icon={<Boxes/>} title="Nenhuma variante encontrada" text="Ajuste os filtros ou registre uma entrada de mercadoria."/>}</section>
    <Drawer open={!!selected} title="Ajustar estoque" subtitle={selected?`${selected.p.name} · ${selected.v.color||'Sem cor'} · ${selected.v.size||'Sem tamanho'}`:''} onClose={()=>setSelected(null)} footer={<><Button onClick={()=>setSelected(null)}>Cancelar</Button><Button variant="primary" loading={busy} onClick={adjust}>Aplicar ajuste</Button></>}><div className="summary-box"><div><span>Quantidade atual</span><strong>{selected?.v.stock||0} un.</strong></div><div><span>Custo médio</span><strong>{money(selected?.v.averageCost||0)}</strong></div></div><div className="form-grid one-col"><Field label="Nova quantidade"><Input type="number" min="0" value={qty} onChange={e=>setQty(Number(e.target.value))}/></Field><Field label="Motivo"><Select value={reason} onChange={e=>setReason(e.target.value)}><option>Contagem de estoque</option><option>Avaria</option><option>Devolução</option><option>Correção manual</option></Select></Field><Field label="Observação"><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Opcional"/></Field></div></Drawer>
  </>
}
