import { Boxes, CheckCircle2, CircleDollarSign, ClipboardCheck, History, Minus, PackageSearch, Plus, SlidersHorizontal, TrendingUp, WalletCards, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useData } from '../context/DataContext';
import { api, notify } from '../lib/api';
import { dateTime, money } from '../lib/format';
import type { InventoryCount, Product, Variant } from '../types';
import { Badge, Button, Drawer, EmptyState, Field, Input, Modal, PageHeader, SearchInput, Select, StatCard, Textarea } from '../components/ui';

export function Inventory({onNewEntry}:{onNewEntry:()=>void}){
  const {data,refresh}=useData();const [tab,setTab]=useState<'stock'|'moves'|'counts'>('stock');const [q,setQ]=useState('');const [filter,setFilter]=useState('all');const [category,setCategory]=useState('');const [selected,setSelected]=useState<{p:Product;v:Variant}|null>(null);const [qty,setQty]=useState(0);const [avgCost,setAvgCost]=useState(0);const [reason,setReason]=useState('Contagem de estoque');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);
  const [countOpen,setCountOpen]=useState(false);const [countTitle,setCountTitle]=useState('Contagem geral');const [countNotes,setCountNotes]=useState('');const [countQ,setCountQ]=useState('');const [counted,setCounted]=useState<Record<string,number>>({});
  const allVariants=useMemo(()=>{const out:Array<{p:Product;v:Variant}>=[];data?.products.filter(p=>p.status==='Ativo').forEach(p=>p.variants.filter(v=>v.active).forEach(v=>out.push({p,v})));return out},[data]);
  const categories=useMemo(()=>[...new Set(allVariants.map(({p})=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')),[allVariants]);
  const rows=useMemo(()=>allVariants.filter(({p,v})=>{const t=`${p.name} ${p.category} ${v.color||''} ${v.size||''} ${v.sku||''}`.toLowerCase();const stockOk=filter==='low'?v.stock<=v.minStock:filter==='zero'?v.stock===0:true;return stockOk&&(!category||p.category===category)&&t.includes(q.toLowerCase())}),[allVariants,q,filter,category]);
  function openAdjust(p:Product,v:Variant,next=v.stock,why='Contagem de estoque',message=''){setSelected({p,v});setQty(Math.max(0,next));setAvgCost(v.averageCost);setReason(why);setNote(message)}
  async function adjust(){if(!selected)return;const qtyChanged=qty!==selected.v.stock;const costChanged=Math.abs(avgCost-selected.v.averageCost)>0.0001;if(!qtyChanged&&!costChanged)return;setBusy(true);try{await api(`/api/inventory/${selected.v.id}/adjust`,{method:'POST',body:JSON.stringify({quantity:qty,averageCost:avgCost,reason,note})});const oldStock=selected.v.stock,oldCost=selected.v.averageCost;setSelected(null);await refresh();if(qtyChanged&&costChanged)notify(`Estoque ${oldStock} → ${qty} un. e custo médio ${money(oldCost)} → ${money(avgCost)}.`);else if(costChanged)notify(`Custo médio corrigido de ${money(oldCost)} para ${money(avgCost)}. O capital em estoque foi recalculado.`);else notify(`Estoque ajustado de ${oldStock} para ${qty} unidades.`)}finally{setBusy(false)}}
  function newCount(){const initial:Record<string,number>={};allVariants.forEach(({v})=>initial[v.id]=v.stock);setCounted(initial);setCountTitle(`Contagem ${new Date().toLocaleDateString('pt-BR')}`);setCountNotes('');setCountQ('');setCountOpen(true)}
  async function saveCount(){setBusy(true);try{await api('/api/inventory/counts',{method:'POST',body:JSON.stringify({title:countTitle,notes:countNotes,items:allVariants.map(({v})=>({variantId:v.id,countedQuantity:Math.max(0,Number(counted[v.id]??v.stock))}))})});setCountOpen(false);await refresh();setTab('counts');notify('Contagem salva como rascunho. Revise as diferenças antes de aplicar.')}finally{setBusy(false)}}
  async function applyCount(c:InventoryCount){setBusy(true);try{await api(`/api/inventory/counts/${c.id}/apply`,{method:'POST'});await refresh();notify('Inventário aplicado e movimentações registradas.')}finally{setBusy(false)}}
  async function cancelCount(c:InventoryCount){setBusy(true);try{await api(`/api/inventory/counts/${c.id}/cancel`,{method:'POST'});await refresh();notify('Contagem cancelada.')}finally{setBusy(false)}}
  const s=data?.summary;const potentialMargin=s?.stockPotentialRevenue?((s.stockPotentialProfit/s.stockPotentialRevenue)*100):0;const filteredCount=allVariants.filter(({p,v})=>`${p.name} ${p.category} ${v.color||''} ${v.size||''} ${v.sku||''}`.toLowerCase().includes(countQ.toLowerCase()));const delta=selected?qty-selected.v.stock:0;const costDelta=selected?avgCost-selected.v.averageCost:0;const projectedCapital=selected?qty*avgCost:0;
  return <>
    <PageHeader title="Estoque" subtitle="Disponibilidade, custo real, ajustes, movimentações e conferência física. Toda correção fica registrada." actions={tab==='stock'?<Button variant="primary" onClick={onNewEntry}><Boxes size={16}/>Nova entrada</Button>:tab==='counts'?<Button variant="primary" onClick={newCount}><Plus size={16}/>Nova contagem</Button>:undefined}/>
    <div className="product-detail-tabs"><button className={tab==='stock'?'active':''} onClick={()=>setTab('stock')}>Estoque</button><button className={tab==='moves'?'active':''} onClick={()=>setTab('moves')}>Movimentações</button><button className={tab==='counts'?'active':''} onClick={()=>setTab('counts')}>Inventários</button></div>
    {tab==='stock'&&<>{s&&<><div className="stats-grid four inventory-money-grid"><StatCard label="Capital em estoque" value={money(s.stockCost)} note="Estoque atual × custo médio real" icon={<WalletCards size={17}/>}/><StatCard label="Faturamento potencial à vista" value={money(s.stockPotentialRevenue)} note="Se todo estoque vender pelo preço Pix/à vista" icon={<CircleDollarSign size={17}/>}/><StatCard label="Lucro bruto potencial" value={money(s.stockPotentialProfit)} note={`${potentialMargin.toFixed(1)}% de margem potencial`} icon={<TrendingUp size={17}/>}/><StatCard label="Peças disponíveis" value={`${s.stockUnits} un.`} note="Somatório das variantes ativas" icon={<Boxes size={17}/>}/></div><div className="stock-projection-note"><strong>Controle conectado</strong><span>Entradas e compras formam o custo médio real; vendas baixam estoque; trocas/devoluções corrigem automaticamente. Se quantidade ou custo estiverem errados, use Ajustar para registrar a correção sem apagar o histórico.</span></div></>}
      <div className="toolbar toolbar-split"><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar produto, cor, tamanho ou SKU..."/><Select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas as categorias</option>{categories.map(c=><option value={c} key={c}>{c}</option>)}</Select><Select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todo o estoque</option><option value="low">Estoque baixo</option><option value="zero">Sem estoque</option></Select></div>
      <section className="table-panel">{rows.length?<div className="table-scroll"><table><thead><tr><th>Produto</th><th>Cor</th><th>Tamanho</th><th>SKU</th><th>Quantidade</th><th>Custo médio</th><th>À vista/Pix</th><th>Cartão</th><th>Capital na variante</th><th>Lucro potencial</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.map(({p,v})=><tr key={v.id}><td><div className="entity"><div className="entity-icon">{v.imageUrl||p.imageUrl?<img className="entity-image" src={v.imageUrl||p.imageUrl||''} alt=""/>:<PackageSearch size={16}/>}</div><div><strong>{p.name}</strong><span>{p.category}</span></div></div></td><td>{v.color||'—'}</td><td>{v.size||'—'}</td><td className="muted-cell">{v.sku||'—'}</td><td><strong>{v.stock}</strong> un.</td><td>{money(v.averageCost)}</td><td>{money(v.cashPrice)}</td><td>{money(v.cardPrice)}</td><td>{money(v.stock*v.averageCost)}</td><td className="positive">{money(v.stock*Math.max(0,v.cashPrice-v.averageCost))}</td><td><Badge tone={v.stock===0?'danger':v.stock<=v.minStock?'warning':'success'}>{v.stock===0?'Sem estoque':v.stock<=v.minStock?'Baixo':'Disponível'}</Badge></td><td><div className="row-actions"><button className="icon-btn" disabled={v.stock<=0} onClick={()=>openAdjust(p,v,v.stock-1,'Saída manual','Retirada rápida de 1 unidade')} title="Diminuir 1 unidade"><Minus size={15}/></button><button className="icon-btn" onClick={()=>openAdjust(p,v)} title="Ajustar quantidade ou custo médio"><SlidersHorizontal size={15}/></button></div></td></tr>)}</tbody></table></div>:<EmptyState icon={<Boxes/>} title="Nenhuma variante encontrada" text="Ajuste a busca, categoria ou situação do estoque."/>}</section></>}
    {tab==='moves'&&<><div className="toolbar"><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar produto, referência ou motivo..."/></div><section className="table-panel">{data?.movements.length?<div className="table-scroll"><table><thead><tr><th>Data</th><th>Produto</th><th>Variante</th><th>Movimento</th><th>Quantidade</th><th>Custo</th><th>Referência</th></tr></thead><tbody>{data.movements.filter(m=>`${m.productName} ${m.color||''} ${m.size||''} ${m.note||''} ${m.referenceId||''}`.toLowerCase().includes(q.toLowerCase())).map(m=>{const costAdjustment=m.referenceType==='cost_adjustment';return <tr key={m.id}><td>{dateTime(m.createdAt)}</td><td><strong>{m.productName}</strong></td><td>{[m.color,m.size].filter(Boolean).join(' · ')||'—'}</td><td><Badge tone={costAdjustment?'info':m.quantity>0?'success':m.quantity<0?'warning':'neutral'}>{costAdjustment?'Custo corrigido':m.type}</Badge></td><td className={m.quantity>0?'positive':m.quantity<0?'negative':''}><strong>{costAdjustment?'—':`${m.quantity>0?'+':''}${m.quantity}`}</strong></td><td>{m.unitCost===null?'—':money(m.unitCost)}</td><td>{m.note||m.referenceId||'—'}</td></tr>})}</tbody></table></div>:<EmptyState icon={<History/>} title="Sem movimentações" text="Entradas, vendas, devoluções e ajustes aparecerão aqui."/>}</section></>}
    {tab==='counts'&&<section className="table-panel">{data?.inventoryCounts.length?<div className="table-scroll"><table><thead><tr><th>Contagem</th><th>Data</th><th>Itens</th><th>Divergências</th><th>Status</th><th></th></tr></thead><tbody>{data.inventoryCounts.map(c=>{const diffs=c.items.filter(i=>i.difference!==0);return <tr key={c.id}><td><strong>{c.title}</strong></td><td>{dateTime(c.createdAt)}</td><td>{c.items.length}</td><td className={diffs.length?'negative':''}>{diffs.length} variantes · {diffs.reduce((a,i)=>a+Math.abs(i.difference),0)} un.</td><td><Badge tone={c.status==='Aplicado'?'success':c.status==='Cancelado'?'neutral':'warning'}>{c.status}</Badge></td><td><div className="row-actions">{c.status==='Rascunho'&&<><Button className="btn-compact" disabled={busy} onClick={()=>void applyCount(c)}><CheckCircle2 size={14}/>Aplicar</Button><button className="icon-btn danger-icon" onClick={()=>void cancelCount(c)} title="Cancelar"><X size={14}/></button></>}</div></td></tr>})}</tbody></table></div>:<EmptyState icon={<ClipboardCheck/>} title="Nenhum inventário" text="Faça uma contagem física para comparar o estoque real com o sistema." action={<Button onClick={newCount}>Nova contagem</Button>}/>}</section>}
    <Drawer open={!!selected} title="Ajustar estoque e custo" subtitle={selected?`${selected.p.name} · ${selected.v.color||'Sem cor'} · ${selected.v.size||'Sem tamanho'}`:''} onClose={()=>setSelected(null)} footer={<><Button onClick={()=>setSelected(null)}>Cancelar</Button><Button variant="primary" loading={busy} disabled={!selected||(qty===selected.v.stock&&Math.abs(avgCost-selected.v.averageCost)<0.0001)} onClick={adjust}>Aplicar ajuste</Button></>}>
      {selected&&<><div className="stock-adjust-preview"><div><span>Quantidade atual</span><strong>{selected.v.stock} un.</strong></div><div><span>Nova quantidade</span><strong>{qty} un. <small className={delta<0?'negative':delta>0?'positive':''}>{delta===0?'':`(${delta>0?'+':''}${delta})`}</small></strong></div><div><span>Custo médio atual</span><strong>{money(selected.v.averageCost)}</strong></div><div><span>Novo custo médio</span><strong>{money(avgCost)} <small className={costDelta<0?'negative':costDelta>0?'positive':''}>{Math.abs(costDelta)<0.0001?'':`(${costDelta>0?'+':''}${money(costDelta)})`}</small></strong></div></div><div className="stock-projection-note"><strong>Capital desta variante após o ajuste: {money(projectedCapital)}</strong><span>Corrigir custo altera a valorização do estoque atual e o custo das vendas futuras. Vendas antigas mantêm o custo histórico que tinham quando foram registradas.</span></div><div className="quick-stock-actions"><Button disabled={qty<=0} onClick={()=>{setQty(v=>Math.max(0,v-1));setReason('Saída manual')}}><Minus size={14}/>-1</Button><Button onClick={()=>{setQty(v=>v+1);setReason('Correção manual')}}><Plus size={14}/>+1</Button><Button onClick={()=>{setQty(0);setReason('Correção manual')}}>Zerar</Button></div><div className="section-divider"/></>}
      <div className="form-grid one-col"><Field label="Nova quantidade"><Input type="number" min="0" value={qty} onChange={e=>setQty(Math.max(0,Number(e.target.value)))}/></Field><Field label="Custo médio real" helper="Use somente para corrigir um custo cadastrado errado. Entradas e compras recalculam este valor automaticamente."><Input type="number" min="0" step=".01" value={avgCost} onChange={e=>{setAvgCost(Math.max(0,Number(e.target.value)));setReason('Correção de custo')}}/></Field><Field label="Motivo"><Select value={reason} onChange={e=>setReason(e.target.value)}><option>Saída manual</option><option>Contagem de estoque</option><option>Avaria</option><option>Devolução</option><option>Correção manual</option><option>Correção de custo</option></Select></Field><Field label="Observação"><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Explique a retirada ou correção quando necessário"/></Field></div>
    </Drawer>
    <Modal open={countOpen} wide title="Nova contagem física" subtitle="Digite o que existe de verdade. O sistema mostra as divergências antes de alterar o estoque." onClose={()=>setCountOpen(false)} footer={<><Button onClick={()=>setCountOpen(false)}>Cancelar</Button><Button variant="primary" loading={busy} onClick={()=>void saveCount()}>Salvar rascunho</Button></>}><div className="form-grid" style={{marginBottom:12}}><Field label="Nome da contagem"><Input value={countTitle} onChange={e=>setCountTitle(e.target.value)}/></Field><Field label="Observações"><Input value={countNotes} onChange={e=>setCountNotes(e.target.value)}/></Field></div><SearchInput value={countQ} onChange={e=>setCountQ(e.target.value)} placeholder="Filtrar produto, categoria, cor, tamanho ou SKU..."/><div className="count-grid">{filteredCount.map(({p,v})=>{const current=Number(counted[v.id]??v.stock),diff=current-v.stock;return <div className="count-row" key={v.id}><div><strong>{p.name}</strong><span>{[v.color,v.size].filter(Boolean).join(' · ')||'Sem variação'} · {v.sku||'sem SKU'}</span></div><div><span>Sistema</span><strong>{v.stock}</strong></div><Field label="Contado"><Input type="number" min="0" value={current} onChange={e=>setCounted(x=>({...x,[v.id]:Math.max(0,Number(e.target.value))}))}/></Field><div className={diff===0?'':'count-diff'}><span>Diferença</span><strong>{diff>0?'+':''}{diff}</strong></div></div>})}</div></Modal>
  </>;
}
