import { CalendarDays, CheckCircle2, GripVertical, History, MapPin, MessageCircle, Pencil, Plus, ReceiptText, Trash2 } from 'lucide-react';
import { useState, type DragEvent } from 'react';
import { useData } from '../context/DataContext';
import { api, notify } from '../lib/api';
import { money, dateTime, shortDate, whatsAppUrl } from '../lib/format';
import type { OrderStatus, Sale } from '../types';
import { Badge, Button, ConfirmDialog, EmptyState, Field, Input, Modal, PageHeader, Select, Textarea } from '../components/ui';

const activeColumns:OrderStatus[]=['Separando','Pronto'];
function orderMessage(s:Sale){const first=s.customerName.split(' ')[0];if(s.orderStatus==='Pronto')return `Oi, ${first}! Seu pedido ${s.number} da YVIE está pronto${s.deliveryMethod==='Retirada'?' para retirada':' para a próxima etapa da entrega'}. Valor do pedido: ${money(s.total)}.${s.amountDue>0?` Valor a pagar: ${money(s.amountDue)}.`:''}`;if(s.orderStatus==='Entregue')return `Oi, ${first}! Registramos o pedido ${s.number} como entregue. Obrigada por comprar com a YVIE!`;return `Oi, ${first}! Recebemos seu pedido ${s.number} na YVIE e ele já está em separação. Valor do pedido: ${money(s.total)}.${s.promisedDate?` Previsão: ${shortDate(s.promisedDate)}.`:''}`}
export function Orders({onNewOrder}:{onNewOrder:()=>void}){
  const {data,refresh}=useData();const [tab,setTab]=useState<'active'|'done'>('active');const [detail,setDetail]=useState<Sale|null>(null);const [editing,setEditing]=useState(false);const [deliveryMethod,setDeliveryMethod]=useState('Retirada');const [deliveryAddress,setDeliveryAddress]=useState('');const [promisedDate,setPromisedDate]=useState('');const [orderNotes,setOrderNotes]=useState('');const [busy,setBusy]=useState(false);const [del,setDel]=useState<Sale|null>(null);
  async function drop(e:DragEvent,status:OrderStatus){e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(!id)return;await api(`/api/sales/${id}/status`,{method:'PATCH',body:JSON.stringify({orderStatus:status})});await refresh();if(status==='Entregue')notify('Pedido entregue. Ele saiu do quadro operacional e foi para Concluídos.')}
  function openDetail(s:Sale){setDetail(s);setEditing(false);setDeliveryMethod(s.deliveryMethod||'Retirada');setDeliveryAddress(s.deliveryAddress||'');setPromisedDate(s.promisedDate||'');setOrderNotes(s.orderNotes||'')}
  async function saveDetails(){if(!detail)return;setBusy(true);try{await api(`/api/sales/${detail.id}/details`,{method:'PATCH',body:JSON.stringify({deliveryMethod,deliveryAddress,promisedDate,orderNotes})});await refresh();setDetail(d=>d?{...d,deliveryMethod,deliveryAddress:deliveryAddress||null,promisedDate:promisedDate||null,orderNotes:orderNotes||null}:d);setEditing(false);notify('Ficha do pedido atualizada.')}finally{setBusy(false)}}
  async function remove(){if(!del)return;setBusy(true);try{await api(`/api/sales/${del.id}`,{method:'DELETE'});setDel(null);setDetail(null);await refresh();notify('Pedido excluído. Estoque, recebíveis e crédito foram revertidos quando necessário.')}finally{setBusy(false)}}
  const done=data?.sales.filter(s=>s.orderStatus==='Entregue'||s.orderStatus==='Cancelado')||[];
  return <><PageHeader title="Pedidos" subtitle="Cadastre, acompanhe no Kanban e abra a ficha para entrega, pagamento, WhatsApp, crédito e itens." actions={<Button variant="primary" onClick={onNewOrder}><Plus size={16}/>Novo pedido</Button>}/>
    <div className="product-detail-tabs order-tabs"><button className={tab==='active'?'active':''} onClick={()=>setTab('active')}>Em andamento</button><button className={tab==='done'?'active':''} onClick={()=>setTab('done')}>Concluídos <span>{done.length}</span></button></div>
    {tab==='active'?<div className="kanban kanban-operational">{activeColumns.map(col=>{const rows=data?.sales.filter(s=>s.orderStatus===col)||[];return <section className="kanban-column" key={col} onDragOver={e=>e.preventDefault()} onDrop={e=>void drop(e,col)}><header><div><span className={`status-dot dot-${col.toLowerCase()}`}/><strong>{col}</strong></div><b>{rows.length}</b></header><div className="kanban-list">{rows.map(s=><OrderCard sale={s} key={s.id} onOpen={()=>openDetail(s)}/>)}</div></section>})}<section className="kanban-column delivery-column" onDragOver={e=>e.preventDefault()} onDrop={e=>void drop(e,'Entregue')}><header><div><span className="status-dot dot-entregue"/><strong>Entregar</strong></div><CheckCircle2 size={15}/></header><div className="delivery-drop"><CheckCircle2 size={30}/><strong>Arraste o pedido pronto para cá</strong><span>Ao concluir, ele sai deste quadro e fica salvo em Concluídos.</span></div></section></div>:done.length?<section className="table-panel"><div className="table-scroll"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Status</th><th>Pagamento</th><th>Total</th><th>Crédito</th><th>Criado em</th><th>Entregue em</th><th></th></tr></thead><tbody>{done.map(s=><tr key={s.id}><td><strong>{s.number}</strong></td><td>{s.customerName}</td><td><Badge tone={s.orderStatus==='Entregue'?'success':'danger'}>{s.orderStatus}</Badge></td><td><Badge tone={s.paymentStatus==='Pago'?'success':'warning'}>{s.paymentStatus}</Badge> <span className="cell-sub">{s.paymentMethod}</span></td><td>{money(s.total)}</td><td>{s.creditUsed?money(s.creditUsed):'—'}</td><td>{dateTime(s.createdAt)}</td><td>{s.deliveredAt?dateTime(s.deliveredAt):'—'}</td><td><button className="icon-btn" title="Abrir ficha" onClick={()=>openDetail(s)}><ReceiptText size={15}/></button></td></tr>)}</tbody></table></div></section>:<EmptyState icon={<History/>} title="Nenhum pedido concluído" text="Pedidos entregues ou cancelados aparecerão aqui e não ocuparão o quadro operacional."/>}
    <Modal open={!!detail} wide title={detail?.number||'Pedido'} subtitle={detail?`${detail.customerName} · ${dateTime(detail.createdAt)}`:''} onClose={()=>{setDetail(null);setEditing(false)}} footer={detail?<><Button onClick={()=>{setDetail(null);setEditing(false)}}>Fechar</Button><a className="btn btn-secondary" href={whatsAppUrl(detail.customerPhone,orderMessage(detail))} target="_blank" rel="noreferrer"><MessageCircle size={15}/>WhatsApp</a>{!editing?<Button onClick={()=>setEditing(true)}><Pencil size={14}/>Editar ficha</Button>:<Button variant="primary" loading={busy} onClick={()=>void saveDetails()}>Salvar ficha</Button>}<Button variant="danger" onClick={()=>setDel(detail)}><Trash2 size={14}/>Excluir pedido</Button></>:undefined}>
      {detail&&<div className="order-detail-sheet"><div className="order-detail-kpis"><article><span>Status</span><Badge tone={detail.orderStatus==='Entregue'?'success':detail.orderStatus==='Pronto'?'info':detail.orderStatus==='Cancelado'?'danger':'warning'}>{detail.orderStatus}</Badge></article><article><span>Valor do pedido</span><strong>{money(detail.total)}</strong></article><article><span>Crédito usado</span><strong>{money(detail.creditUsed)}</strong></article><article><span>A pagar</span><strong>{money(detail.amountDue)}</strong></article></div>
        <div className="order-detail-grid"><section className="subpanel"><div className="subpanel-title"><div><h3>Cliente e pagamento</h3><span>{detail.customerPhone}</span></div><MessageCircle size={17}/></div><div className="result-sheet"><div><span>Cliente</span><strong>{detail.customerName}</strong></div><div><span>Pagamento</span><strong>{detail.paymentMethod}</strong></div><div><span>Situação</span><Badge tone={detail.paymentStatus==='Pago'?'success':'warning'}>{detail.paymentStatus}</Badge></div><div><span>Subtotal</span><strong>{money(detail.subtotal)}</strong></div><div><span>Desconto</span><strong>{money(detail.discount)}</strong></div></div></section>
        <section className="subpanel"><div className="subpanel-title"><div><h3>Entrega</h3><span>Dados operacionais do pedido.</span></div><MapPin size={17}/></div>{editing?<div className="form-grid one-col"><Field label="Modalidade"><Select value={deliveryMethod} onChange={e=>setDeliveryMethod(e.target.value)}><option>Retirada</option><option>Entrega</option><option>Envio</option></Select></Field><Field label="Data prometida"><Input type="date" value={promisedDate} onChange={e=>setPromisedDate(e.target.value)}/></Field>{deliveryMethod!=='Retirada'&&<Field label="Endereço / destino"><Input value={deliveryAddress} onChange={e=>setDeliveryAddress(e.target.value)}/></Field>}<Field label="Observações"><Textarea value={orderNotes} onChange={e=>setOrderNotes(e.target.value)}/></Field></div>:<div className="result-sheet"><div><span>Modalidade</span><strong>{detail.deliveryMethod||'Não informada'}</strong></div><div><span>Previsão</span><strong>{detail.promisedDate?shortDate(detail.promisedDate):'—'}</strong></div><div><span>Destino</span><strong>{detail.deliveryAddress||'—'}</strong></div><div className="order-notes-line"><span>Observações</span><strong>{detail.orderNotes||'—'}</strong></div></div>}</section></div>
        <section className="subpanel"><div className="subpanel-title"><div><h3>Itens do pedido</h3><span>{detail.items.reduce((a,i)=>a+i.quantity,0)} peças</span></div><CalendarDays size={17}/></div><div className="detail-items">{detail.items.map(i=><div key={i.id}><div><strong>{i.quantity}× {i.productName}</strong><span>{[i.color,i.size].filter(Boolean).join(' · ')||'Sem variação'} · {money(i.unitPrice)} cada</span></div><strong>{money(i.quantity*i.unitPrice)}</strong></div>)}</div></section>
      </div>}
    </Modal>
    <ConfirmDialog open={!!del} title="Excluir este pedido?" text="O pedido desaparecerá das telas. O sistema reverte o efeito líquido no estoque, cancela recebíveis e estorna crédito usado ou gerado. Os movimentos de auditoria permanecem registrados. A exclusão é bloqueada se não puder ser revertida com segurança." onClose={()=>setDel(null)} onConfirm={remove} busy={busy}/>
  </>
}
function OrderCard({sale,onOpen}:{sale:Sale;onOpen:()=>void}){return <article className="order-card" draggable onClick={onOpen} onDragStart={e=>e.dataTransfer.setData('text/plain',sale.id)}><div className="order-card-head"><div><strong>{sale.customerName}</strong><span>{sale.number}{sale.promisedDate?` · ${shortDate(sale.promisedDate)}`:''}</span></div><GripVertical size={16}/></div><div className="order-card-items">{sale.items.slice(0,3).map(i=><span key={i.id}>{i.quantity}× {i.productName} · {[i.color,i.size].filter(Boolean).join(' ')}</span>)}</div><footer><div><strong>{money(sale.total)}</strong><Badge tone={sale.paymentStatus==='Pago'?'success':'warning'}>{sale.paymentMethod}</Badge></div><span>{sale.deliveryMethod||dateTime(sale.createdAt)}</span></footer></article>}
