import { Archive, ArrowLeft, BadgeDollarSign, Copy, ImagePlus, PackagePlus, Pencil, Plus, Shirt, Sparkles, Trash2, X } from 'lucide-react';
import { useMemo, useState, type ChangeEvent } from 'react';
import { Badge, Button, ConfirmDialog, Drawer, EmptyState, Field, Input, PageHeader, SearchInput, Select } from '../components/ui';
import { useData } from '../context/DataContext';
import { api, notify } from '../lib/api';
import { dateTime, money, shortDate } from '../lib/format';
import type { Product } from '../types';

type VariantDraft={id?:string;color:string;size:string;stock:number;minStock:number;averageCost:number;salePrice:number;sku:string;active:boolean;imageKey:string|null;imageUrl:string|null};
type ProductForm={name:string;category:string;collection:string;status:'Ativo'|'Arquivado';imageKey:string|null;imageUrl:string|null};
const newVariant=(color='',size=''):VariantDraft=>({color,size,stock:0,minStock:1,averageCost:0,salePrice:0,sku:'',active:true,imageKey:null,imageUrl:null});
const blankForm=():ProductForm=>({name:'',category:'',collection:'',status:'Ativo',imageKey:null,imageUrl:null});
const cleanList=(value:string)=>[...new Set(value.split(/[,;\n]/).map(x=>x.trim()).filter(Boolean))];
const margin=(price:number,cost:number)=>price>0?((price-cost)/price)*100:0;

export function Products({onNewEntry,onPricing}:{onNewEntry:(productId:string)=>void;onPricing:(productId:string)=>void}){
  const {data,refresh}=useData();
  const [q,setQ]=useState('');const [category,setCategory]=useState('');const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Product|null>(null);
  const [form,setForm]=useState<ProductForm>(blankForm());const [variants,setVariants]=useState<VariantDraft[]>([newVariant()]);
  const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState('');const [archive,setArchive]=useState<Product|null>(null);const [deleteTarget,setDeleteTarget]=useState<Product|null>(null);const [selectedId,setSelectedId]=useState('');const [tab,setTab]=useState<'overview'|'variants'|'entries'|'sales'|'pricing'>('overview');
  const [generatorColors,setGeneratorColors]=useState('');const [generatorSizes,setGeneratorSizes]=useState('');
  const categories=useMemo(()=>[...new Set((data?.products||[]).map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')),[data]);
  const rows=useMemo(()=>data?.products.filter(p=>{const text=`${p.name} ${p.category} ${p.collection||''}`.toLowerCase();return(!category||p.category===category)&&text.includes(q.toLowerCase())})||[],[data,q,category]);
  const selected=data?.products.find(p=>p.id===selectedId)||null;

  function create(){setEditing(null);setForm(blankForm());setVariants([newVariant()]);setGeneratorColors('');setGeneratorSizes('');setOpen(true)}
  function edit(p:Product){setEditing(p);setForm({name:p.name,category:p.category,collection:p.collection||'',status:p.status,imageKey:p.imageKey,imageUrl:p.imageUrl});setVariants(p.variants.filter(v=>v.active).map(v=>({id:v.id,color:v.color||'',size:v.size||'',stock:v.stock,minStock:v.minStock,averageCost:v.averageCost,salePrice:v.salePrice,sku:v.sku||'',active:v.active,imageKey:v.imageKey,imageUrl:v.imageUrl})));setGeneratorColors('');setGeneratorSizes('');setOpen(true)}
  function changeVariant(index:number,key:keyof VariantDraft,value:string|number|boolean|null){setVariants(v=>v.map((row,i)=>i===index?{...row,[key]:value}:row))}
  function generateVariants(){
    const colors=cleanList(generatorColors);const sizes=cleanList(generatorSizes);const cs=colors.length?colors:[''];const ss=sizes.length?sizes:[''];
    setVariants(current=>{const next=[...current];const existing=new Set(current.map(v=>`${v.color.toLowerCase()}::${v.size.toLowerCase()}`));cs.forEach(color=>ss.forEach(size=>{const k=`${color.toLowerCase()}::${size.toLowerCase()}`;if(!existing.has(k)){next.push(newVariant(color,size));existing.add(k)}}));return next.filter((v,i)=>i>0||v.color||v.size||v.stock||v.sku)});
    setGeneratorColors('');setGeneratorSizes('');
  }
  async function uploadImage(file:File,target:string,onDone:(image:{key:string;url:string})=>void){
    if(file.size>5*1024*1024){notify('A imagem deve ter no máximo 5 MB.','error');return}
    setUploading(target);try{const fd=new FormData();fd.append('file',file);const result=await api<{key:string;url:string}>('/api/media',{method:'POST',body:fd});onDone(result);notify('Imagem enviada com sucesso.')}finally{setUploading('')}
  }
  async function save(){if(!form.name.trim())return;setBusy(true);try{const {imageUrl:_,...productData}=form;void _;const cleanVariants=variants.map(({imageUrl,...v})=>v);await api(editing?`/api/products/${editing.id}`:'/api/products',{method:editing?'PUT':'POST',body:JSON.stringify({...productData,variants:cleanVariants})});setOpen(false);await refresh();notify(`Produto ${editing?'atualizado':'cadastrado'} com sucesso.`)}finally{setBusy(false)}}
  async function duplicate(p:Product){setBusy(true);try{await api(`/api/products/${p.id}/duplicate`,{method:'POST'});await refresh();notify(`${p.name} foi duplicado sem copiar estoque ou SKU.`)}finally{setBusy(false)}}
  async function doArchive(){if(!archive)return;setBusy(true);try{await api(`/api/products/${archive.id}/archive`,{method:'POST'});setArchive(null);if(selectedId===archive.id)setSelectedId('');await refresh();notify('Produto arquivado sem apagar o histórico.')}finally{setBusy(false)}}
  async function doDelete(){if(!deleteTarget)return;const target=deleteTarget;setBusy(true);try{const result=await api<{mode:'deleted'|'archived'}>(`/api/products/${target.id}`,{method:'DELETE'});setDeleteTarget(null);if(selectedId===target.id)setSelectedId('');await refresh();notify(result.mode==='deleted'?'Produto excluído definitivamente.':'O produto possui histórico e foi arquivado com segurança.')}finally{setBusy(false)}}

  if(selected){
    const active=selected.variants.filter(v=>v.active);const units=active.reduce((a,v)=>a+v.stock,0);const stockCost=active.reduce((a,v)=>a+v.stock*v.averageCost,0);const potential=active.reduce((a,v)=>a+v.stock*v.cashPrice,0);const stockProfit=potential-stockCost;
    const sales=(data?.sales||[]).filter(s=>s.orderStatus!=='Cancelado'&&s.items.some(i=>i.productId===selected.id));const sold=sales.flatMap(s=>s.items).filter(i=>i.productId===selected.id).reduce((a,i)=>a+i.quantity,0);const revenue=sales.flatMap(s=>s.items).filter(i=>i.productId===selected.id).reduce((a,i)=>a+i.quantity*i.unitPrice,0);const gross=sales.flatMap(s=>s.items).filter(i=>i.productId===selected.id).reduce((a,i)=>a+i.quantity*(i.unitPrice-i.unitCost),0);const entries=(data?.entries||[]).filter(e=>e.productId===selected.id);const history=(data?.pricing||[]).filter(r=>r.productId===selected.id);
    const prices=active.map(v=>v.cashPrice).filter(Boolean);const minPrice=prices.length?Math.min(...prices):0,maxPrice=prices.length?Math.max(...prices):0;
    return <>
      <div className="product-detail-head"><button className="entry-back" onClick={()=>setSelectedId('')}><ArrowLeft size={17}/></button><div className="product-detail-photo">{selected.imageUrl?<img src={selected.imageUrl} alt={selected.name}/>:<Shirt size={22}/>}</div><div className="product-detail-copy"><span>{selected.category}{selected.collection?` · ${selected.collection}`:''}</span><h1>{selected.name}</h1><p>{units} unidades disponíveis · {active.length} variantes</p></div><div className="product-detail-actions"><Button onClick={()=>onNewEntry(selected.id)}><PackagePlus size={15}/>Nova entrada</Button><Button onClick={()=>onPricing(selected.id)}><BadgeDollarSign size={15}/>Precificar</Button><Button variant="primary" onClick={()=>edit(selected)}><Pencil size={15}/>Editar</Button><button className="icon-btn" title="Duplicar" onClick={()=>duplicate(selected)}><Copy size={15}/></button><button className="icon-btn" title="Arquivar" onClick={()=>setArchive(selected)}><Archive size={15}/></button><button className="icon-btn danger-icon" title="Excluir produto" onClick={()=>setDeleteTarget(selected)}><Trash2 size={15}/></button></div></div>
      <div className="product-detail-tabs">{([['overview','Visão geral'],['variants','Variantes'],['entries','Entradas'],['sales','Vendas'],['pricing','Precificação']] as const).map(([k,label])=><button className={tab===k?'active':''} key={k} onClick={()=>setTab(k)}>{label}</button>)}</div>
      {tab==='overview'&&<div className="product-overview"><section className="product-kpis"><article><span>Capital em estoque</span><strong>{money(stockCost)}</strong><small>{units} unidades disponíveis</small></article><article><span>Faturamento potencial à vista</span><strong>{money(potential)}</strong><small>{minPrice===maxPrice?money(minPrice):`${money(minPrice)} – ${money(maxPrice)}`} por peça</small></article><article><span>Lucro potencial</span><strong>{money(stockProfit)}</strong><small>Se vender todo o estoque à vista</small></article><article><span>Lucro já realizado</span><strong>{money(gross)}</strong><small>{sold} peças vendidas · {money(revenue)} faturados</small></article></section><div className="product-overview-grid"><section className="panel"><div className="panel-head"><div><h2>Estoque por variante</h2><p>Disponibilidade e preços sem abrir outra tela.</p></div></div><div className="product-variant-summary">{active.map(v=><div key={v.id}><div className="variant-summary-with-photo"><span className="tiny-product-photo">{v.imageUrl||selected.imageUrl?<img src={v.imageUrl||selected.imageUrl||''} alt=""/>:<Shirt size={13}/>}</span><div><strong>{[v.color,v.size].filter(Boolean).join(' · ')||'Sem variação'}</strong><span>{v.sku||'Sem SKU'}</span></div></div><div><strong>{v.stock} un.</strong><span>Pix {money(v.cashPrice)} · Cartão {money(v.cardPrice)}</span></div></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Últimos movimentos comerciais</h2><p>Vendas e entradas recentes do produto.</p></div></div><div className="product-timeline">{[...entries.slice(0,3).map(e=>({date:e.createdAt,title:`Entrada · ${e.totalUnits} un.`,sub:e.description,value:money(e.totalCost)})),...sales.slice(0,3).map(s=>({date:s.createdAt,title:`Venda ${s.number}`,sub:s.customerName,value:money(s.items.filter(i=>i.productId===selected.id).reduce((a,i)=>a+i.quantity*i.unitPrice,0))}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map((x,i)=><div key={`${x.title}-${i}`}><span></span><div><strong>{x.title}</strong><small>{x.sub} · {dateTime(x.date)}</small></div><b>{x.value}</b></div>)}</div></section></div></div>}
      {tab==='variants'&&<section className="table-panel"><div className="table-scroll"><table><thead><tr><th>Variante</th><th>SKU</th><th>Estoque</th><th>Custo médio</th><th>À vista/Pix</th><th>Cartão</th><th>Margem à vista</th><th>Status</th></tr></thead><tbody>{active.map(v=><tr key={v.id}><td><div className="entity"><div className="entity-icon">{v.imageUrl||selected.imageUrl?<img className="entity-image" src={v.imageUrl||selected.imageUrl||''} alt=""/>:<Shirt size={15}/>}</div><strong>{[v.color,v.size].filter(Boolean).join(' · ')||'Sem variação'}</strong></div></td><td>{v.sku||'—'}</td><td>{v.stock} un.</td><td>{money(v.averageCost)}</td><td>{money(v.cashPrice)}</td><td>{money(v.cardPrice)}</td><td><span className={margin(v.cashPrice,v.averageCost)<40?'negative':'positive'}>{margin(v.cashPrice,v.averageCost).toFixed(1)}%</span></td><td><Badge tone={v.stock===0?'danger':v.stock<=v.minStock?'warning':'success'}>{v.stock===0?'Sem estoque':v.stock<=v.minStock?'Baixo':'Disponível'}</Badge></td></tr>)}</tbody></table></div></section>}
      {tab==='entries'&&(entries.length?<section className="table-panel"><div className="table-scroll"><table><thead><tr><th>Data</th><th>Descrição</th><th>Unidades</th><th>Custo total</th><th>Custo médio lote</th></tr></thead><tbody>{entries.map(e=><tr key={e.id}><td>{shortDate(e.entryDate)}</td><td>{e.description}</td><td>{e.totalUnits}</td><td>{money(e.totalCost)}</td><td>{money(e.totalUnits?e.totalCost/e.totalUnits:0)}</td></tr>)}</tbody></table></div></section>:<EmptyState icon={<PackagePlus/>} title="Sem entradas" text="Ainda não há lotes registrados para este produto." action={<Button onClick={()=>onNewEntry(selected.id)}>Registrar entrada</Button>}/>) }
      {tab==='sales'&&(sales.length?<section className="table-panel"><div className="table-scroll"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Data</th><th>Quantidade</th><th>Faturamento do produto</th></tr></thead><tbody>{sales.map(s=>{const its=s.items.filter(i=>i.productId===selected.id);return <tr key={s.id}><td><strong>{s.number}</strong></td><td>{s.customerName}</td><td>{dateTime(s.createdAt)}</td><td>{its.reduce((a,i)=>a+i.quantity,0)}</td><td>{money(its.reduce((a,i)=>a+i.quantity*i.unitPrice,0))}</td></tr>})}</tbody></table></div></section>:<EmptyState icon={<Shirt/>} title="Sem vendas" text="Este produto ainda não apareceu em uma venda."/>)}
      {tab==='pricing'&&<div className="product-pricing-tab"><section className="table-panel"><div className="table-scroll"><table><thead><tr><th>Variante</th><th>Custo médio</th><th>À vista/Pix</th><th>Cartão</th><th>Margem à vista</th><th>Última precificação</th></tr></thead><tbody>{active.map(v=>{const last=history.find(h=>h.variantId===v.id);return <tr key={v.id}><td><strong>{[v.color,v.size].filter(Boolean).join(' · ')||'Sem variação'}</strong></td><td>{money(v.averageCost)}</td><td>{money(v.cashPrice)}</td><td>{money(v.cardPrice)}</td><td>{margin(v.cashPrice,v.averageCost).toFixed(1)}%</td><td>{last?dateTime(last.createdAt):'—'}</td></tr>})}</tbody></table></div></section><Button variant="primary" onClick={()=>onPricing(selected.id)}><BadgeDollarSign size={15}/>Abrir calculadora de precificação</Button></div>}
      <ConfirmDialog open={!!archive} title="Arquivar produto?" text="Só é possível arquivar sem estoque. O histórico é preservado e o produto sai das novas operações." onClose={()=>setArchive(null)} onConfirm={doArchive} busy={busy}/>
      <ConfirmDialog open={!!deleteTarget} title="Excluir produto?" text="Se o produto nunca participou de vendas, entradas, compras, inventários ou precificações, ele será apagado definitivamente junto com o estoque cadastrado por engano. Se já houver histórico, o ERP preservará os registros: com estoque zero ele será arquivado; com estoque disponível a exclusão será bloqueada até você ajustar o estoque." onClose={()=>setDeleteTarget(null)} onConfirm={doDelete} busy={busy}/>
      {renderDrawer()}
    </>;
  }

  function renderDrawer(){return <Drawer open={open} title={editing?'Editar produto':'Novo produto'} subtitle={editing?'Dados comerciais e visuais. Estoque e custo de variantes existentes são controlados por Estoque, Entradas e Compras.':'Gere combinações de cor e tamanho sem cadastrar uma por uma.'} onClose={()=>setOpen(false)} footer={<><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="primary" loading={busy} onClick={save}>Salvar produto</Button></>}>
    <ImagePicker label="Foto principal do produto" imageUrl={form.imageUrl} busy={uploading==='product'} onChange={file=>void uploadImage(file,'product',image=>setForm(f=>({...f,imageKey:image.key,imageUrl:image.url})))} onRemove={()=>setForm(f=>({...f,imageKey:null,imageUrl:null}))}/>
    <div className="form-grid"><Field label="Nome" required className="span-2"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Categoria"><Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Blusas, calças..."/></Field><Field label="Coleção"><Input value={form.collection} onChange={e=>setForm({...form,collection:e.target.value})}/></Field><Field label="Status" className="span-2"><Select value={form.status} onChange={e=>setForm({...form,status:e.target.value as ProductForm['status']})}><option>Ativo</option><option>Arquivado</option></Select></Field></div>
    <div className="section-divider"/><div className="section-title-row"><div><h3>Gerador de variantes</h3><p>Ex.: 3 cores × 5 tamanhos = 15 combinações em um clique.</p></div><Sparkles size={17}/></div><div className="variant-generator compact"><div className="variant-generator-fields"><Field label="Cores"><Input value={generatorColors} onChange={e=>setGeneratorColors(e.target.value)} placeholder="Preto, Branco, Vinho"/></Field><Field label="Tamanhos"><Input value={generatorSizes} onChange={e=>setGeneratorSizes(e.target.value)} placeholder="P, M, G"/></Field><Button onClick={generateVariants} disabled={!generatorColors.trim()&&!generatorSizes.trim()}><Plus size={14}/>Gerar</Button></div></div>
    <div className="section-divider"/><div className="section-title-row"><div><h3>Variantes</h3><p>A foto da variante é opcional; sem ela, o sistema usa a foto principal ou o ícone.</p></div><Button onClick={()=>setVariants(v=>[...v,newVariant()])}><Plus size={14}/>Adicionar</Button></div>
    <div className="variant-card-editor">{variants.map((v,i)=><article className="variant-edit-card" key={v.id||i}><div className="variant-edit-head"><div className="variant-edit-title"><span className="tiny-product-photo">{v.imageUrl||form.imageUrl?<img src={v.imageUrl||form.imageUrl||''} alt=""/>:<Shirt size={13}/>}</span><strong>Variante {i+1}</strong></div><button className="icon-btn" onClick={()=>setVariants(x=>x.filter((_,n)=>n!==i))} disabled={variants.length===1}>×</button></div><div className="variant-image-line"><ImagePicker compact label="Foto da variante" imageUrl={v.imageUrl} busy={uploading===`variant-${i}`} onChange={file=>void uploadImage(file,`variant-${i}`,image=>setVariants(list=>list.map((row,n)=>n===i?{...row,imageKey:image.key,imageUrl:image.url}:row)))} onRemove={()=>setVariants(list=>list.map((row,n)=>n===i?{...row,imageKey:null,imageUrl:null}:row))}/></div><div className="form-grid"><Field label="Cor"><Input value={v.color} onChange={e=>changeVariant(i,'color',e.target.value)}/></Field><Field label="Tamanho"><Input value={v.size} onChange={e=>changeVariant(i,'size',e.target.value)}/></Field><Field label={v.id?'Estoque atual':'Qtd. inicial'} helper={v.id?'Use Estoque → Ajustar quantidade ou registre uma Entrada.':undefined}><Input type="number" min="0" value={v.stock} disabled={!!v.id} onChange={e=>changeVariant(i,'stock',Number(e.target.value))}/></Field><Field label="Estoque mínimo"><Input type="number" min="0" value={v.minStock} onChange={e=>changeVariant(i,'minStock',Number(e.target.value))}/></Field><Field label={v.id?'Custo médio atual':'Custo inicial'} helper={v.id?'Recalculado automaticamente por Entradas, Compras e devoluções.':undefined}><Input type="number" min="0" step=".01" value={v.averageCost} disabled={!!v.id} onChange={e=>changeVariant(i,'averageCost',Number(e.target.value))}/></Field><Field label="Preço base/à vista"><Input type="number" min="0" step=".01" value={v.salePrice} onChange={e=>changeVariant(i,'salePrice',Number(e.target.value))}/></Field><Field label="SKU" className="span-2"><Input value={v.sku} onChange={e=>changeVariant(i,'sku',e.target.value)}/></Field></div></article>)}</div>
  </Drawer>}

  return <>
    <PageHeader title="Produtos" subtitle="O produto concentra estoque, entradas, vendas, fotos e precificação em uma única página." actions={<Button variant="primary" onClick={create}><Plus size={16}/>Novo produto</Button>}/>
    <div className="toolbar toolbar-split"><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar produto, coleção ou categoria..."/><Select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas as categorias</option>{categories.map(c=><option value={c} key={c}>{c}</option>)}</Select></div>
    {rows.length?<div className="product-grid">{rows.map(p=>{const active=p.variants.filter(v=>v.active);const units=active.reduce((a,v)=>a+v.stock,0);const potential=active.reduce((a,v)=>a+v.stock*v.cashPrice,0);return <button className="product-card product-card-button" key={p.id} onClick={()=>{setSelectedId(p.id);setTab('overview')}}><div className="product-card-top"><div className={`product-icon ${p.imageUrl?'has-image':''}`}>{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<Shirt size={20}/>}</div><Badge tone={p.status==='Ativo'?'success':'neutral'}>{p.status}</Badge></div><h3>{p.name}</h3><p>{p.category}{p.collection?` · ${p.collection}`:''}</p><div className="product-metrics"><div><span>Estoque</span><strong>{units} un.</strong></div><div><span>Variantes</span><strong>{active.length}</strong></div><div><span>Potencial à vista</span><strong>{money(potential)}</strong></div></div><div className="product-open-line"><span>Abrir produto</span><ArrowLeft size={14}/></div></button>})}</div>:<EmptyState icon={<Shirt/>} title="Nenhum produto" text="Nenhum produto corresponde à busca ou categoria selecionada." action={<Button onClick={create}>Cadastrar produto</Button>}/>} 
    {renderDrawer()}
    <ConfirmDialog open={!!archive} title="Arquivar produto?" text="Só é possível arquivar sem estoque. O histórico será preservado." onClose={()=>setArchive(null)} onConfirm={doArchive} busy={busy}/>
    <ConfirmDialog open={!!deleteTarget} title="Excluir produto?" text="Produtos sem histórico são apagados de verdade. Produtos com histórico são preservados e arquivados quando o estoque está zerado." onClose={()=>setDeleteTarget(null)} onConfirm={doDelete} busy={busy}/>
  </>;
}

function ImagePicker({label,imageUrl,busy,onChange,onRemove,compact=false}:{label:string;imageUrl:string|null;busy:boolean;onChange:(file:File)=>void;onRemove:()=>void;compact?:boolean}){
  function pick(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(file)onChange(file);e.target.value=''}
  return <div className={`image-picker ${compact?'compact':''}`}><div className="image-picker-preview">{imageUrl?<img src={imageUrl} alt="Prévia do produto"/>:<ImagePlus size={compact?18:24}/>}</div><div className="image-picker-copy"><strong>{label}</strong><span>Opcional · JPG, PNG, WEBP ou AVIF · até 5 MB</span><label className={`btn btn-secondary image-picker-button ${busy?'disabled':''}`}><ImagePlus size={14}/>{busy?'Enviando...':imageUrl?'Trocar foto':'Adicionar foto'}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={pick} disabled={busy}/></label>{imageUrl&&<button type="button" className="image-remove" onClick={onRemove}><X size={13}/>Remover foto</button>}</div></div>
}
