import { Archive, Copy, Pencil, Plus, Shirt } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useData } from '../context/DataContext';
import { api } from '../lib/api';
import { money } from '../lib/format';
import type { Product } from '../types';
import { Badge, Button, ConfirmDialog, Drawer, EmptyState, Field, Input, PageHeader, SearchInput, Select } from '../components/ui';

type VariantDraft={id?:string;color:string;size:string;stock:number;minStock:number;averageCost:number;salePrice:number;sku:string;active:boolean};
const newVariant=():VariantDraft=>({color:'',size:'',stock:0,minStock:1,averageCost:0,salePrice:0,sku:'',active:true});
export function Products(){
  const {data,refresh}=useData(); const [q,setQ]=useState('');const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Product|null>(null);const [form,setForm]=useState({name:'',category:'',collection:'',status:'Ativo'});const [variants,setVariants]=useState<VariantDraft[]>([newVariant()]);const [busy,setBusy]=useState(false);const [archive,setArchive]=useState<Product|null>(null);
  const rows=useMemo(()=>data?.products.filter(p=>`${p.name} ${p.category} ${p.collection||''}`.toLowerCase().includes(q.toLowerCase()))||[],[data,q]);
  function create(){setEditing(null);setForm({name:'',category:'',collection:'',status:'Ativo'});setVariants([newVariant()]);setOpen(true)}
  function edit(p:Product){setEditing(p);setForm({name:p.name,category:p.category,collection:p.collection||'',status:p.status});setVariants(p.variants.map(v=>({id:v.id,color:v.color||'',size:v.size||'',stock:v.stock,minStock:v.minStock,averageCost:v.averageCost,salePrice:v.salePrice,sku:v.sku||'',active:v.active})));setOpen(true)}
  function changeVariant(index:number,key:keyof VariantDraft,value:string|number|boolean){setVariants(v=>v.map((row,i)=>i===index?{...row,[key]:value}:row))}
  async function save(){if(!form.name.trim())return;setBusy(true);try{await api(editing?`/api/products/${editing.id}`:'/api/products',{method:editing?'PUT':'POST',body:JSON.stringify({...form,variants})});setOpen(false);await refresh()}finally{setBusy(false)}}
  async function duplicate(p:Product){setBusy(true);try{await api(`/api/products/${p.id}/duplicate`,{method:'POST'});await refresh()}finally{setBusy(false)}}
  async function doArchive(){if(!archive)return;setBusy(true);try{await api(`/api/products/${archive.id}/archive`,{method:'POST'});setArchive(null);await refresh()}finally{setBusy(false)}}
  return <>
    <PageHeader title="Produtos" subtitle="Cadastros estruturais, variantes, preços e organização do catálogo." actions={<Button variant="primary" onClick={create}><Plus size={16}/>Novo produto</Button>}/>
    <div className="toolbar"><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar produto ou categoria..."/></div>
    {rows.length?<div className="product-grid">{rows.map(p=>{const units=p.variants.filter(v=>v.active).reduce((a,v)=>a+v.stock,0);const potential=p.variants.filter(v=>v.active).reduce((a,v)=>a+v.stock*v.salePrice,0);return <article className="product-card" key={p.id}><div className="product-card-top"><div className="product-icon"><Shirt size={20}/></div><Badge tone={p.status==='Ativo'?'success':'neutral'}>{p.status}</Badge></div><h3>{p.name}</h3><p>{p.category}{p.collection?` · ${p.collection}`:''}</p><div className="product-metrics"><div><span>Estoque</span><strong>{units} un.</strong></div><div><span>Variantes</span><strong>{p.variants.filter(v=>v.active).length}</strong></div><div><span>Potencial</span><strong>{money(potential)}</strong></div></div><div className="card-actions"><Button onClick={()=>edit(p)}><Pencil size={14}/>Editar</Button><button className="icon-btn" title="Duplicar" onClick={()=>duplicate(p)}><Copy size={15}/></button><button className="icon-btn danger-icon" title="Arquivar" onClick={()=>setArchive(p)}><Archive size={15}/></button></div></article>})}</div>:<EmptyState icon={<Shirt/>} title="Nenhum produto" text="Cadastre o catálogo e depois registre entradas de estoque." action={<Button onClick={create}>Cadastrar produto</Button>}/>} 
    <Drawer open={open} title={editing?'Editar produto':'Novo produto'} subtitle="Cor e tamanho são livres. Use apenas o que fizer sentido para a peça." onClose={()=>setOpen(false)} footer={<><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="primary" loading={busy} onClick={save}>Salvar produto</Button></>}>
      <div className="form-grid"><Field label="Nome" required className="span-2"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Categoria"><Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Blusas, calças..."/></Field><Field label="Coleção"><Input value={form.collection} onChange={e=>setForm({...form,collection:e.target.value})}/></Field><Field label="Status" className="span-2"><Select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Ativo</option><option>Arquivado</option></Select></Field></div>
      <div className="section-divider"/><div className="section-title-row"><div><h3>Variantes</h3><p>Cadastre combinações de cor, tamanho e preço sem campos engessados.</p></div><Button onClick={()=>setVariants(v=>[...v,newVariant()])}><Plus size={14}/>Linha</Button></div>
      <div className="variant-editor">{variants.map((v,i)=><div className="variant-row" key={v.id||i}><Input placeholder="Cor" value={v.color} onChange={e=>changeVariant(i,'color',e.target.value)}/><Input placeholder="Tamanho" value={v.size} onChange={e=>changeVariant(i,'size',e.target.value)}/><Input title="Quantidade" type="number" min="0" value={v.stock} onChange={e=>changeVariant(i,'stock',Number(e.target.value))}/><Input title="Custo" type="number" min="0" step="0.01" value={v.averageCost} onChange={e=>changeVariant(i,'averageCost',Number(e.target.value))}/><Input title="Venda" type="number" min="0" step="0.01" value={v.salePrice} onChange={e=>changeVariant(i,'salePrice',Number(e.target.value))}/><Input placeholder="SKU" value={v.sku} onChange={e=>changeVariant(i,'sku',e.target.value)}/><button className="icon-btn" onClick={()=>setVariants(x=>x.filter((_,n)=>n!==i))} disabled={variants.length===1}>×</button></div>)}</div>
      <div className="variant-legend"><span>Cor</span><span>Tamanho</span><span>Qtd.</span><span>Custo</span><span>Venda</span><span>SKU</span><span></span></div>
    </Drawer>
    <ConfirmDialog open={!!archive} title="Arquivar produto?" text="O histórico será preservado e o produto deixará de aparecer como ativo nas novas operações." onClose={()=>setArchive(null)} onConfirm={doArchive} busy={busy}/>
  </>
}
