import { ArrowLeft, Check, PackageCheck, Plus, RotateCcw, Search, ShoppingCart, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Badge, Button, ConfirmDialog, EmptyState, Field, Input, PageHeader, Select, Textarea } from '../components/ui';
import { useData } from '../context/DataContext';
import { api, notify } from '../lib/api';
import { money, shortDate } from '../lib/format';
import type { Purchase } from '../types';

type DraftItem={variantId:string;productId:string;productName:string;variantLabel:string;quantity:number;unitCost:number;stock:number};
export function Purchases(){
  const {data,refresh}=useData();
  const [creating,setCreating]=useState(false);const [supplierId,setSupplierId]=useState('');const [purchaseDate,setPurchaseDate]=useState(new Date().toISOString().slice(0,10));const [freight,setFreight]=useState(0);const [other,setOther]=useState(0);const [notes,setNotes]=useState('');const [query,setQuery]=useState('');const [items,setItems]=useState<DraftItem[]>([]);const [busy,setBusy]=useState(false);const [filter,setFilter]=useState('');const [receiveTarget,setReceiveTarget]=useState<Purchase|null>(null);const [cancelTarget,setCancelTarget]=useState<Purchase|null>(null);const [reverseTarget,setReverseTarget]=useState<Purchase|null>(null);
  const variants=useMemo(()=>data?.products.flatMap(p=>p.status==='Ativo'?p.variants.filter(v=>v.active).map(v=>({p,v})):[])||[],[data]);
  const filtered=variants.filter(({p,v})=>`${p.name} ${p.category} ${v.color||''} ${v.size||''} ${v.sku||''}`.toLowerCase().includes(query.toLowerCase())).slice(0,40);
  const reversedPurchases=useMemo(()=>new Set((data?.movements||[]).filter(m=>m.referenceType==='purchase_reversal').map(m=>m.referenceId).filter(Boolean)),[data]);
  const purchaseState=(p:Purchase)=>reversedPurchases.has(p.id)?'Estornado':p.status;
  const subtotal=items.reduce((a,i)=>a+i.quantity*i.unitCost,0),total=subtotal+freight+other,units=items.reduce((a,i)=>a+i.quantity,0);
  function reset(){setCreating(false);setSupplierId('');setPurchaseDate(new Date().toISOString().slice(0,10));setFreight(0);setOther(0);setNotes('');setQuery('');setItems([])}
  function add(productId:string,variantId:string){const p=data?.products.find(x=>x.id===productId),v=p?.variants.find(x=>x.id===variantId);if(!p||!v)return;setItems(current=>{const found=current.find(i=>i.variantId===variantId);if(found)return current.map(i=>i.variantId===variantId?{...i,quantity:i.quantity+1}:i);return [...current,{variantId,productId,productName:p.name,variantLabel:[v.color,v.size].filter(Boolean).join(' · ')||'Sem variação',quantity:1,unitCost:v.averageCost,stock:v.stock}]})}
  async function save(){if(!supplierId||!items.length)return;setBusy(true);try{await api('/api/purchases',{method:'POST',body:JSON.stringify({supplierId,purchaseDate,freightCost:freight,otherCost:other,notes,items:items.map(i=>({variantId:i.variantId,quantity:i.quantity,unitCost:i.unitCost}))})});reset();await refresh();notify('Compra registrada. O estoque só será alterado quando ela for recebida.')}finally{setBusy(false)}}
  async function receive(){if(!receiveTarget)return;const p=receiveTarget;setBusy(true);try{await api(`/api/purchases/${p.id}/receive`,{method:'POST'});setReceiveTarget(null);await refresh();notify('Compra recebida e estoque atualizado.')}finally{setBusy(false)}}
  async function cancel(){if(!cancelTarget)return;const p=cancelTarget;setBusy(true);try{await api(`/api/purchases/${p.id}/cancel`,{method:'POST'});setCancelTarget(null);await refresh();notify('Compra cancelada. Nenhuma peça entrou no estoque.')}finally{setBusy(false)}}
  async function reverse(){if(!reverseTarget)return;const p=reverseTarget;setBusy(true);try{await api(`/api/purchases/${p.id}/reverse`,{method:'POST'});setReverseTarget(null);await refresh();notify('Recebimento estornado. Estoque e custo médio voltaram ao estado anterior.')}finally{setBusy(false)}}

  if(creating)return <div className="purchase-workspace">
    <div className="entry-workspace-head"><button className="entry-back" onClick={reset}><ArrowLeft size={17}/></button><div><span>Compras</span><h1>Nova compra</h1><p>Registre o pedido agora e dê entrada no estoque somente quando a mercadoria chegar.</p></div></div>
    <div className="purchase-builder-grid"><div className="purchase-builder-main">
      <section className="entry-section"><div className="entry-section-head"><div><h2>1. Dados da compra</h2><p>Fornecedor, data e custos adicionais.</p></div></div><div className="form-grid"><Field label="Fornecedor" required><Select value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Selecione...</option>{data?.suppliers.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></Field><Field label="Data"><Input type="date" value={purchaseDate} onChange={e=>setPurchaseDate(e.target.value)}/></Field><Field label="Frete"><Input type="number" min="0" step=".01" value={freight} onChange={e=>setFreight(Number(e.target.value))}/></Field><Field label="Outros custos"><Input type="number" min="0" step=".01" value={other} onChange={e=>setOther(Number(e.target.value))}/></Field><Field label="Observações" className="span-2"><Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Prazo, referência do pedido, condições..."/></Field></div></section>
      <section className="entry-section"><div className="entry-section-head"><div><h2>2. Adicionar peças</h2><p>Busque qualquer variante já cadastrada.</p></div></div><div className="purchase-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto, cor, tamanho ou SKU..."/></div><div className="purchase-product-results">{filtered.map(({p,v})=><button key={v.id} onClick={()=>add(p.id,v.id)}><div className="purchase-thumb">{v.imageUrl||p.imageUrl?<img src={v.imageUrl||p.imageUrl||''} alt=""/>:<ShoppingCart size={16}/>}</div><div><strong>{p.name}</strong><span>{[v.color,v.size].filter(Boolean).join(' · ')||'Sem variação'} · estoque atual {v.stock}</span></div><b>{money(v.averageCost)}</b><Plus size={15}/></button>)}</div></section>
    </div><aside className="purchase-cart-panel"><div className="sale-summary-head"><h3>Itens da compra</h3><span>{units} un.</span></div><div className="purchase-cart-list">{items.length?items.map(item=><div className="purchase-cart-item" key={item.variantId}><div><strong>{item.productName}</strong><span>{item.variantLabel}</span></div><button className="icon-btn" onClick={()=>setItems(x=>x.filter(i=>i.variantId!==item.variantId))}><X size={14}/></button><Field label="Qtd."><Input type="number" min="1" value={item.quantity} onChange={e=>setItems(x=>x.map(i=>i.variantId===item.variantId?{...i,quantity:Math.max(1,Number(e.target.value))}:i))}/></Field><Field label="Custo unit."><Input type="number" min="0" step=".01" value={item.unitCost} onChange={e=>setItems(x=>x.map(i=>i.variantId===item.variantId?{...i,unitCost:Number(e.target.value)}:i))}/></Field><strong className="purchase-line-total">{money(item.quantity*item.unitCost)}</strong></div>):<div className="cart-empty">Adicione os produtos comprados.</div>}</div><div className="sale-totals"><div><span>Mercadorias</span><strong>{money(subtotal)}</strong></div><div><span>Frete</span><strong>{money(freight)}</strong></div><div><span>Outros custos</span><strong>{money(other)}</strong></div><div className="grand-total"><span>Total investido</span><strong>{money(total)}</strong></div></div><Button variant="primary" loading={busy} disabled={!supplierId||!items.length} onClick={save}><Check size={15}/>Salvar compra</Button></aside></div>
  </div>;

  const rows=(data?.purchases||[]).filter(p=>!filter||purchaseState(p)===filter);
  return <><PageHeader title="Compras" subtitle="Pedidos a fornecedores, custo real e recebimento integrado ao estoque." actions={<Button variant="primary" onClick={()=>setCreating(true)}><Plus size={16}/>Nova compra</Button>}/><div className="toolbar toolbar-split"><div></div><Select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas as compras</option><option>Pedido</option><option>Recebido</option><option>Cancelado</option><option>Estornado</option></Select></div><section className="table-panel">{rows.length?<div className="table-scroll"><table><thead><tr><th>Compra</th><th>Fornecedor</th><th>Data</th><th>Itens</th><th>Mercadorias</th><th>Frete + extras</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(p=>{const state=purchaseState(p);return <tr key={p.id}><td><strong>{p.number}</strong></td><td>{p.supplierName}</td><td>{shortDate(p.purchaseDate)}</td><td>{p.totalUnits} un.</td><td>{money(p.itemsSubtotal)}</td><td>{money(p.freightCost+p.otherCost)}</td><td><strong>{money(p.totalCost)}</strong></td><td><Badge tone={state==='Recebido'?'success':state==='Pedido'?'warning':'danger'}>{state}</Badge></td><td><div className="row-actions">{state==='Pedido'&&<><Button className="btn-compact" onClick={()=>setReceiveTarget(p)} disabled={busy}><PackageCheck size={14}/>Receber</Button><button className="icon-btn danger-icon" title="Cancelar compra antes do recebimento" onClick={()=>setCancelTarget(p)}><X size={14}/></button></>}{state==='Recebido'&&<Button className="btn-compact" onClick={()=>setReverseTarget(p)} disabled={busy}><RotateCcw size={14}/>Estornar</Button>}</div></td></tr>})}</tbody></table></div>:<EmptyState icon={<ShoppingCart/>} title="Nenhuma compra registrada" text="Crie um pedido de compra e receba-o quando a mercadoria chegar." action={<Button onClick={()=>setCreating(true)}>Registrar compra</Button>}/>}</section><ConfirmDialog open={!!receiveTarget} title="Receber compra?" text={receiveTarget?`${receiveTarget.number}: ${receiveTarget.totalUnits} unidades entrarão no estoque e o custo médio será recalculado incluindo frete e outros custos.`:''} onClose={()=>setReceiveTarget(null)} onConfirm={()=>void receive()} busy={busy}/><ConfirmDialog open={!!cancelTarget} title="Cancelar compra?" text={cancelTarget?`${cancelTarget.number} será cancelada. Como ainda não foi recebida, nenhuma peça será alterada no estoque.`:''} onClose={()=>setCancelTarget(null)} onConfirm={()=>void cancel()} busy={busy}/><ConfirmDialog open={!!reverseTarget} title="Estornar recebimento?" text={reverseTarget?`${reverseTarget.number}: o sistema tentará remover exatamente as ${reverseTarget.totalUnits} unidades que entraram e reconstruir o custo médio anterior. Se alguma dessas variantes teve venda, ajuste ou outra entrada depois do recebimento, o estorno será bloqueado para proteger o estoque.`:''} onClose={()=>setReverseTarget(null)} onConfirm={()=>void reverse()} busy={busy}/></>
}
