import { BarChart3, Boxes, CircleDollarSign, Download, Trophy, Users } from 'lucide-react';
import { useMemo, useState, type ReactNode } from 'react';
import { PeriodFilter, currentMonthRange, inRange } from '../components/PeriodFilter';
import { Button, PageHeader } from '../components/ui';
import { useData } from '../context/DataContext';
import { exportYvieWorkbook } from '../lib/exportWorkbook';
import { money } from '../lib/format';
import { notify } from '../lib/api';

export function Reports(){
  const {data}=useData();const [exporting,setExporting]=useState(false);const [range,setRange]=useState(currentMonthRange());
  const period=useMemo(()=>{if(!data)return null;const sales=data.sales.filter(s=>s.orderStatus!=='Cancelado'&&inRange(s.createdAt,range));const returns=data.returns.filter(r=>inRange(r.createdAt,range));const revenue=sales.reduce((a,s)=>a+s.total,0)-returns.reduce((a,r)=>a+r.refundAmount+r.creditAmount,0);const baseCost=sales.reduce((a,s)=>a+s.costTotal,0);const returnedCost=returns.flatMap(r=>r.items).filter(i=>i.direction==='Entrada').reduce((a,i)=>a+i.quantity*i.unitCost,0);const exchangeCost=returns.flatMap(r=>r.items).filter(i=>i.direction==='Saída').reduce((a,i)=>a+i.quantity*i.unitCost,0);const gross=revenue-(baseCost-returnedCost+exchangeCost);return{sales,revenue,gross,ticket:sales.length?revenue/sales.length:0}},[data,range]);
  if(!data||!period)return null;const current=data;
  const sold=current.products.map(p=>({name:p.name,qty:period.sales.flatMap(s=>s.items).filter(i=>i.productId===p.id).reduce((a,i)=>a+i.quantity,0)})).sort((a,b)=>b.qty-a.qty);const max=Math.max(1,...sold.map(x=>x.qty));
  const customers=current.customers.map(c=>({name:c.name,total:period.sales.filter(s=>s.customerId===c.id).reduce((a,s)=>a+s.total,0)})).sort((a,b)=>b.total-a.total);const cmax=Math.max(1,...customers.map(x=>x.total));
  async function exportExcel(){setExporting(true);try{await exportYvieWorkbook(current);notify('Planilha Excel completa gerada.')}finally{setExporting(false)}}
  return <><PageHeader title="Relatórios" subtitle="Indicadores por período, estoque atual e exportação completa da operação." actions={<div className="report-actions"><PeriodFilter value={range} onChange={setRange}/><Button variant="primary" loading={exporting} onClick={()=>void exportExcel()}><Download size={16}/>Exportar Excel</Button></div>}/><div className="reports-grid"><Report icon={<CircleDollarSign/>} title="Faturamento" value={money(period.revenue)} text={range.label}/><Report icon={<CircleDollarSign/>} title="Margem bruta" value={`${period.revenue?((period.gross/period.revenue)*100).toFixed(1):'0.0'}%`} text="Após custos, trocas e devoluções do período."/><Report icon={<Boxes/>} title="Capital no estoque" value={money(current.summary.stockCost)} text={`${current.summary.stockUnits} unidades disponíveis agora.`}/><Report icon={<CircleDollarSign/>} title="Lucro potencial do estoque" value={money(current.summary.stockPotentialProfit)} text={`Faturamento potencial ${money(current.summary.stockPotentialRevenue)}.`}/><Report icon={<BarChart3/>} title="Ticket médio" value={money(period.ticket)} text={`Média de ${period.sales.length} vendas no período.`}/><Report icon={<CircleDollarSign/>} title="A receber" value={money(current.summary.receivablePending)} text="Saldo ainda pendente de clientes."/><section className="report-card wide"><div className="report-title"><Trophy size={17}/><div><h3>Produtos mais vendidos</h3><p>Quantidade de peças no período.</p></div></div><div className="bars">{sold.slice(0,6).map(x=><div className="bar-row" key={x.name}><span>{x.name}</span><div><i style={{width:`${x.qty/max*100}%`}}/></div><strong>{x.qty}</strong></div>)}</div></section><section className="report-card wide"><div className="report-title"><Users size={17}/><div><h3>Clientes com maior compra</h3><p>Valor comprado no período.</p></div></div><div className="bars">{customers.slice(0,6).map(x=><div className="bar-row" key={x.name}><span>{x.name}</span><div><i style={{width:`${x.total/cmax*100}%`}}/></div><strong>{money(x.total)}</strong></div>)}</div></section></div></>}
function Report({icon,title,value,text}:{icon:ReactNode;title:string;value:string;text:string}){return <article className="report-card"><div className="report-title">{icon}<div><h3>{title}</h3><p>{text}</p></div></div><strong className="report-value">{value}</strong></article>}
