import { ArrowDownLeft, ArrowUpRight, Plus, Repeat2, Search, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Badge, Button, EmptyState, Field, Input, Modal, PageHeader, Select, Textarea } from '../components/ui';
import { useData } from '../context/DataContext';
import { api, notify } from '../lib/api';
import { dateTime, money } from '../lib/format';

type ExchangeDraft={productId:string;variantId:string;productName:string;label:string;quantity:number;unitPrice:number;stock:number};
export function Returns(){
  const {data,refresh}=useData();const [open,setOpen]=useState(false);const [saleId,setSaleId]=useState('');const [type,setType]=useState<'Devolução'|'Troca'>('Devolução');const [returned,setReturned]=useState<Record<string,number>>({});const [exchange,setExchange]=useState<ExchangeDraft[]>([]);const [q,setQ]=useState('');const [refund,setRefund]=useState<number|null>(null);const [credit,setCredit]=useState(0);const [notes,setNotes]=useState('');const [busy,setBusy]=useState(false);
  const sale=data?.sales.find(s=>s.id===saleId)||null;
  const returnedBefore=useMemo(()=>{const map:Record<string,number>={};(data?.returns||[]).filter(r=>r.saleId===saleId).flatMap(r=>r.items).filter(i=>i.direction==='Entrada'&&i.saleItemId).forEach(i=>{map[i.saleItemId!]=(map[i.saleItemId!]||0)+i.quantity});return map},[data,saleId]);
  const variants=useMemo(()=>data?.products.flatMap(p=>p.status==='Ativo'?p.variants.filter(v=>v.active&&v.stock>0).map(v=>({p,v})):[])||[],[data]);
  const filtered=variants.filter(({p,v})=>`${p.name} ${v.color||''} ${v.size||''} ${v.sku||''}`.toLowerCase().includes(q.toLowerCase())).slice(0,28);
  const returnedValue=sale?sale.items.reduce((a,i)=>a+Math.min(returned[i.id]||0,Math.max(0,i.quantity-(returnedBefore[i.id]||0)))*i.unitPrice,0):0;const exchangeValue=exchange.reduce((a,i)=>a+i.quantity*i.unitPrice,0);const suggested=Math.max(0,returnedValue-exchangeValue);
  function reset(){setOpen(false);setSaleId('');setType('Devolução');setReturned({});setExchange([]);setQ('');setRefund(null);setCredit(0);setNotes('')}
  function addExchange(productId:string,variantId:string){const p=data?.products.find(x=>x.id===productId),v=p?.variants.find(x=>x.id===variantId);if(!p||!v)return;setExchange(rows=>{const found=rows.find(i=>i.variantId===variantId);if(found)return rows.map(i=>i.variantId===variantId?{...i,quantity:Math.min(i.stock,i.quantity+1)}:i);return [...rows,{productId,variantId,productName:p.name,label:[v.color,v.size].filter(Boolean).join(' · ')||'Sem variação',quantity:1,unitPrice:v.salePrice,stock:v.stock}]})}
  async function save(){if(!sale||!Object.values(returned).some(n=>n>0))return;setBusy(true);try{await api(`/api/sales/${sale.id}/returns`,{method:'POST',body:JSON.stringify({type,returnedItems:Object.entries(returned).filter(([,n])=>n>0).map(([saleItemId,quantity])=>({saleItemId,quantity})),exchangeItems:type==='Troca'?exchange.map(i=>({productId:i.productId,variantId:i.variantId,quantity:i.quantity,unitPrice:i.unitPrice})):[],refundAmount:refund===null?suggested:refund,creditAmount:credit,notes})});reset();await refresh();notify(`${type} registrada e estoque atualizado.`)}finally{setBusy(false)}}
  return <>
    <PageHeader title="Trocas e devoluções" subtitle="Devolva apenas as peças necessárias, ajuste o estoque e registre substituições sem cancelar a venda inteira." actions={<Button variant="primary" onClick={()=>setOpen(true)}><Repeat2 size={16}/>Nova troca/devolução</Button>}/>
    <section className="table-panel">{data?.returns.length?<div className="table-scroll"><table><thead><tr><th>Registro</th><th>Pedido</th><th>Cliente</th><th>Tipo</th><th>Peças que voltaram</th><th>Peças que saíram</th><th>Reembolso</th><th>Crédito</th><th>Data</th></tr></thead><tbody>{data.returns.map(r=><tr key={r.id}><td><strong>{r.number}</strong></td><td>{r.saleNumber}</td><td>{r.customerName}</td><td><Badge tone={r.type==='Troca'?'info':'warning'}>{r.type}</Badge></td><td>{r.items.filter(i=>i.direction==='Entrada').reduce((a,i)=>a+i.quantity,0)} un.</td><td>{r.items.filter(i=>i.direction==='Saída').reduce((a,i)=>a+i.quantity,0)} un.</td><td>{money(r.refundAmount)}</td><td>{money(r.creditAmount)}</td><td>{dateTime(r.createdAt)}</td></tr>)}</tbody></table></div>:<EmptyState icon={<Repeat2/>} title="Nenhuma troca ou devolução" text="Quando uma cliente devolver ou trocar apenas parte de um pedido, registre aqui."/>}</section>
    <Modal open={open} wide title="Nova troca ou devolução" subtitle="Escolha o pedido, o que retorna e, se for troca, quais peças sairão no lugar." onClose={reset} footer={<><Button onClick={reset}>Cancelar</Button><Button variant="primary" loading={busy} disabled={!sale||!Object.values(returned).some(n=>n>0)} onClick={()=>void save()}>Confirmar operação</Button></>}>
      <div className="return-builder"><div className="return-main"><div className="form-grid"><Field label="Pedido" required><Select value={saleId} onChange={e=>{setSaleId(e.target.value);setReturned({});setExchange([]);setRefund(null)}}><option value="">Selecione...</option>{data?.sales.filter(s=>s.orderStatus!=='Cancelado').map(s=><option key={s.id} value={s.id}>{s.number} · {s.customerName}</option>)}</Select></Field><Field label="Operação"><Select value={type} onChange={e=>setType(e.target.value as 'Devolução'|'Troca')}><option>Devolução</option><option>Troca</option></Select></Field></div>
      {sale&&<><div className="section-divider"/><div className="section-title-row"><div><h3>1. Peças que estão voltando</h3><p>O máximo considera devoluções anteriores do mesmo item.</p></div><ArrowDownLeft size={17}/></div><div className="return-item-list">{sale.items.map(i=>{const max=Math.max(0,i.quantity-(returnedBefore[i.id]||0));return <div key={i.id}><div><strong>{i.productName}</strong><span>{[i.color,i.size].filter(Boolean).join(' · ')||'Sem variação'} · vendido por {money(i.unitPrice)}</span></div><Field label={`Qtd. máx. ${max}`}><Input type="number" min="0" max={max} disabled={max===0} value={returned[i.id]||0} onChange={e=>setReturned(x=>({...x,[i.id]:Math.max(0,Math.min(max,Number(e.target.value)))}))}/></Field></div>})}</div></>}
      {sale&&type==='Troca'&&<><div className="section-divider"/><div className="section-title-row"><div><h3>2. Peças que sairão na troca</h3><p>Selecione as novas variantes disponíveis.</p></div><ArrowUpRight size={17}/></div><div className="purchase-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar produto, cor, tamanho ou SKU..."/></div><div className="return-exchange-results">{filtered.map(({p,v})=><button key={v.id} onClick={()=>addExchange(p.id,v.id)}><div><strong>{p.name}</strong><span>{[v.color,v.size].filter(Boolean).join(' · ')||'Sem variação'} · {v.stock} disponíveis</span></div><b>{money(v.salePrice)}</b><Plus size={14}/></button>)}</div><div className="return-exchange-selected">{exchange.map(i=><div key={i.variantId}><div><strong>{i.productName}</strong><span>{i.label}</span></div><Input type="number" min="1" max={i.stock} value={i.quantity} onChange={e=>setExchange(x=>x.map(r=>r.variantId===i.variantId?{...r,quantity:Math.max(1,Math.min(r.stock,Number(e.target.value)))}:r))}/><Input type="number" min="0" step=".01" value={i.unitPrice} onChange={e=>setExchange(x=>x.map(r=>r.variantId===i.variantId?{...r,unitPrice:Number(e.target.value)}:r))}/><button className="icon-btn" onClick={()=>setExchange(x=>x.filter(r=>r.variantId!==i.variantId))}><X size={14}/></button></div>)}</div></>}
      </div><aside className="return-summary"><h3>Resumo</h3><div className="result-sheet"><div><span>Valor que retorna</span><strong>{money(returnedValue)}</strong></div><div><span>Novas peças</span><strong>{money(exchangeValue)}</strong></div><div><span>Diferença sugerida</span><strong>{money(suggested)}</strong></div></div><Field label="Reembolso"><Input type="number" min="0" step=".01" value={refund===null?suggested:refund} onChange={e=>setRefund(Number(e.target.value))}/></Field><Field label="Crédito para cliente"><Input type="number" min="0" step=".01" value={credit} onChange={e=>setCredit(Number(e.target.value))}/></Field><Field label="Observações"><Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Motivo, condição da peça, acerto financeiro..."/></Field></aside></div>
    </Modal>
  </>;
}
