import { ArrowDownLeft, ArrowUpRight, Plus, Repeat2, Search, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Badge, Button, EmptyState, Field, Input, Modal, PageHeader, Select, Textarea } from '../components/ui';
import { useData } from '../context/DataContext';
import { api, notify } from '../lib/api';
import { dateTime, money } from '../lib/format';

type ExchangeDraft={productId:string;variantId:string;productName:string;label:string;quantity:number;unitPrice:number;stock:number};
const isCardMethod=(method:string)=>['Débito','Crédito'].includes(method);

export function Returns({openSignal=0,initialSaleId=''}:{openSignal?:number;initialSaleId?:string}){
  const {data,refresh}=useData();
  const [open,setOpen]=useState(false);const [saleId,setSaleId]=useState('');const [type,setType]=useState<'Devolução'|'Troca'>('Devolução');const [returned,setReturned]=useState<Record<string,number>>({});const [exchange,setExchange]=useState<ExchangeDraft[]>([]);const [q,setQ]=useState('');const [refund,setRefund]=useState<number|null>(null);const [credit,setCredit]=useState(0);const [additionalStatus,setAdditionalStatus]=useState<'Pago'|'Pendente'>('Pago');const [notes,setNotes]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!openSignal)return;setSaleId(initialSaleId);setType('Devolução');setReturned({});setExchange([]);setQ('');setRefund(null);setCredit(0);setAdditionalStatus('Pago');setNotes('');setOpen(true)},[openSignal,initialSaleId]);
  const sale=data?.sales.find(s=>s.id===saleId)||null;const customer=sale?data?.customers.find(c=>c.id===sale.customerId):null;
  const returnedBefore=useMemo(()=>{const map:Record<string,number>={};(data?.returns||[]).filter(r=>r.saleId===saleId).flatMap(r=>r.items).filter(i=>i.direction==='Entrada'&&i.saleItemId).forEach(i=>{map[i.saleItemId!]=(map[i.saleItemId!]||0)+i.quantity});return map},[data,saleId]);
  const pendingDebt=useMemo(()=>data?.receivables.filter(r=>r.saleId===saleId&&r.status==='Pendente').reduce((a,r)=>a+r.amount,0)||0,[data,saleId]);
  const variants=useMemo(()=>data?.products.flatMap(p=>p.status==='Ativo'?p.variants.filter(v=>v.active&&v.stock>0).map(v=>({p,v})):[])||[],[data]);
  const filtered=variants.filter(({p,v})=>`${p.name} ${v.color||''} ${v.size||''} ${v.sku||''}`.toLowerCase().includes(q.toLowerCase())).slice(0,28);
  const discountFactor=sale&&sale.subtotal>0?Math.max(0,Math.min(1,sale.total/sale.subtotal)):1;
  const returnedValue=sale?sale.items.reduce((a,i)=>a+Math.min(returned[i.id]||0,Math.max(0,i.quantity-(returnedBefore[i.id]||0)))*i.unitPrice*discountFactor,0):0;
  const exchangeValue=type==='Troca'?exchange.reduce((a,i)=>a+i.quantity*i.unitPrice,0):0;
  const customerFavor=Math.max(0,returnedValue-exchangeValue);const debtOffset=Math.min(customerFavor,pendingDebt);const available=Math.max(0,customerFavor-debtOffset);const additional=Math.max(0,exchangeValue-returnedValue);
  const refundValue=Math.max(0,Math.min(available,refund===null?available-credit:refund));const creditValue=Math.max(0,Math.min(available-refundValue,credit));const pendingSettlement=Math.max(0,available-refundValue-creditValue);

  function reset(){setOpen(false);setSaleId('');setType('Devolução');setReturned({});setExchange([]);setQ('');setRefund(null);setCredit(0);setAdditionalStatus('Pago');setNotes('')}
  function resetSettlement(){setRefund(null);setCredit(0)}
  function changeType(next:'Devolução'|'Troca'){setType(next);if(next==='Devolução')setExchange([]);resetSettlement()}
  function changeSale(next:string){setSaleId(next);setReturned({});setExchange([]);setRefund(null);setCredit(0);setAdditionalStatus('Pago')}
  function addExchange(productId:string,variantId:string){const p=data?.products.find(x=>x.id===productId),v=p?.variants.find(x=>x.id===variantId);if(!p||!v)return;const unitPrice=sale&&isCardMethod(sale.paymentMethod)?v.cardPrice:v.cashPrice;setExchange(rows=>{const found=rows.find(i=>i.variantId===variantId);if(found)return rows.map(i=>i.variantId===variantId?{...i,quantity:Math.min(i.stock,i.quantity+1)}:i);return [...rows,{productId,variantId,productName:p.name,label:[v.color,v.size].filter(Boolean).join(' · ')||'Sem variação',quantity:1,unitPrice,stock:v.stock}]});resetSettlement()}
  function allRefund(){setCredit(0);setRefund(available)}function allCredit(){setRefund(0);setCredit(available)}
  async function save(){if(!sale||!Object.values(returned).some(n=>n>0)||pendingSettlement>0.009)return;setBusy(true);try{await api(`/api/sales/${sale.id}/returns`,{method:'POST',body:JSON.stringify({type,returnedItems:Object.entries(returned).filter(([,n])=>n>0).map(([saleItemId,quantity])=>({saleItemId,quantity})),exchangeItems:type==='Troca'?exchange.map(i=>({productId:i.productId,variantId:i.variantId,quantity:i.quantity,unitPrice:i.unitPrice})):[],refundAmount:refundValue,creditAmount:creditValue,additionalPaymentStatus:additional>0?additionalStatus:undefined,notes})});reset();await refresh();notify(`${type} registrada. Estoque, custo e financeiro foram sincronizados.`)}finally{setBusy(false)}}

  return <>
    <PageHeader title="Trocas e devoluções" subtitle="Uma única operação ajusta estoque, custo, A receber, reembolso e crédito da cliente." actions={<Button variant="primary" onClick={()=>setOpen(true)}><Repeat2 size={16}/>Nova troca/devolução</Button>}/>
    <section className="table-panel">{data?.returns.length?<div className="table-scroll"><table><thead><tr><th>Registro</th><th>Pedido</th><th>Cliente</th><th>Tipo</th><th>Voltou</th><th>Saiu</th><th>Abatido do A receber</th><th>Reembolso</th><th>Crédito</th><th>Diferença</th><th>Data</th></tr></thead><tbody>{data.returns.map(r=><tr key={r.id}><td><strong>{r.number}</strong></td><td>{r.saleNumber}</td><td>{r.customerName}</td><td><Badge tone={r.type==='Troca'?'info':'warning'}>{r.type}</Badge></td><td>{r.items.filter(i=>i.direction==='Entrada').reduce((a,i)=>a+i.quantity,0)} un.</td><td>{r.items.filter(i=>i.direction==='Saída').reduce((a,i)=>a+i.quantity,0)} un.</td><td>{money(r.debtOffset)}</td><td>{money(r.refundAmount)}</td><td>{money(r.creditAmount)}</td><td>{r.additionalAmount>0?<>{money(r.additionalAmount)} · <Badge tone={r.additionalPaymentStatus==='Pendente'?'warning':'success'}>{r.additionalPaymentStatus||'Pago'}</Badge></>:'—'}</td><td>{dateTime(r.createdAt)}</td></tr>)}</tbody></table></div>:<EmptyState icon={<Repeat2/>} title="Nenhuma troca ou devolução" text="Quando uma cliente devolver ou trocar apenas parte de um pedido, registre aqui."/>}</section>
    <Modal open={open} wide title="Nova troca ou devolução" subtitle="Se houver saldo a receber, a devolução abate a dívida primeiro. Só o restante vira reembolso ou crédito." onClose={reset} footer={<><Button onClick={reset}>Cancelar</Button><Button variant="primary" loading={busy} disabled={!sale||!Object.values(returned).some(n=>n>0)||pendingSettlement>0.009} onClick={()=>void save()}>Confirmar operação</Button></>}>
      <div className="return-builder"><div className="return-main"><div className="form-grid"><Field label="Pedido" required><Select value={saleId} onChange={e=>changeSale(e.target.value)}><option value="">Selecione...</option>{data?.sales.filter(s=>s.orderStatus!=='Cancelado').map(s=><option key={s.id} value={s.id}>{s.number} · {s.customerName}</option>)}</Select></Field><Field label="Operação"><Select value={type} onChange={e=>changeType(e.target.value as 'Devolução'|'Troca')}><option>Devolução</option><option>Troca</option></Select></Field></div>
      {sale&&<><div className="section-divider"/><div className="section-title-row"><div><h3>1. Peças que estão voltando</h3><p>Entram novamente no estoque pelo custo histórico pelo qual saíram. Descontos do pedido são rateados no valor devolvido.</p></div><ArrowDownLeft size={17}/></div><div className="return-item-list">{sale.items.map(i=>{const max=Math.max(0,i.quantity-(returnedBefore[i.id]||0));const effective=i.unitPrice*discountFactor;return <div key={i.id}><div><strong>{i.productName}</strong><span>{[i.color,i.size].filter(Boolean).join(' · ')||'Sem variação'} · valor efetivo {money(effective)}{discountFactor<.999?` (preço cheio ${money(i.unitPrice)})`:''}</span></div><Field label={`Qtd. máx. ${max}`}><Input type="number" min="0" max={max} disabled={max===0} value={returned[i.id]||0} onChange={e=>{setReturned(x=>({...x,[i.id]:Math.max(0,Math.min(max,Number(e.target.value)))}));resetSettlement()}}/></Field></div>})}</div></>}
      {sale&&type==='Troca'&&<><div className="section-divider"/><div className="section-title-row"><div><h3>2. Peças que sairão na troca</h3><p>O preço sugerido acompanha a forma de pagamento do pedido original; a unidade sai do estoque imediatamente.</p></div><ArrowUpRight size={17}/></div><div className="purchase-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar produto, cor, tamanho ou SKU..."/></div><div className="return-exchange-results">{filtered.map(({p,v})=>{const price=sale&&isCardMethod(sale.paymentMethod)?v.cardPrice:v.cashPrice;return <button key={v.id} onClick={()=>addExchange(p.id,v.id)}><div><strong>{p.name}</strong><span>{[v.color,v.size].filter(Boolean).join(' · ')||'Sem variação'} · {v.stock} disponíveis</span></div><b>{money(price)}</b><Plus size={14}/></button>})}</div><div className="return-exchange-selected">{exchange.map(i=><div key={i.variantId}><div><strong>{i.productName}</strong><span>{i.label}</span></div><Input type="number" min="1" max={i.stock} value={i.quantity} onChange={e=>{setExchange(x=>x.map(r=>r.variantId===i.variantId?{...r,quantity:Math.max(1,Math.min(r.stock,Number(e.target.value)))}:r));resetSettlement()}}/><Input type="number" min="0" step=".01" value={i.unitPrice} onChange={e=>{setExchange(x=>x.map(r=>r.variantId===i.variantId?{...r,unitPrice:Number(e.target.value)}:r));resetSettlement()}}/><button className="icon-btn" onClick={()=>{setExchange(x=>x.filter(r=>r.variantId!==i.variantId));resetSettlement()}}><X size={14}/></button></div>)}</div></>}
      </div><aside className="return-summary"><h3>Acerto da operação</h3><div className="result-sheet"><div><span>Mercadorias que voltam</span><strong>{money(returnedValue)}</strong></div><div><span>Mercadorias que saem</span><strong>{money(exchangeValue)}</strong></div>{pendingDebt>0&&<div><span>A receber antes</span><strong>{money(pendingDebt)}</strong></div>}{debtOffset>0&&<div><span>Abatido da dívida</span><strong>- {money(debtOffset)}</strong></div>}<div><span>Disponível para reembolso/crédito</span><strong>{money(available)}</strong></div>{additional>0&&<div><span>Diferença a cobrar</span><strong>{money(additional)}</strong></div>}{customer&&<div><span>Crédito atual cliente</span><strong>{money(customer.creditBalance)}</strong></div>}</div>
      {available>0&&<><div className="inline-actions"><Button onClick={allRefund}>Tudo reembolso</Button><Button onClick={allCredit}>Tudo crédito</Button></div><Field label="Reembolso em dinheiro"><Input type="number" min="0" max={available} step=".01" value={refundValue} onChange={e=>setRefund(Math.max(0,Math.min(available,Number(e.target.value))))}/></Field><Field label="Crédito para próxima compra" helper="Entra no saldo da cliente e pode ser usado em um novo pedido"><Input type="number" min="0" max={Math.max(0,available-refundValue)} step=".01" value={creditValue} onChange={e=>setCredit(Math.max(0,Math.min(Math.max(0,available-refundValue),Number(e.target.value))))}/></Field>{pendingSettlement>0.009&&<div className="danger-note">Ainda faltam definir {money(pendingSettlement)} entre reembolso e crédito.</div>}</>}
      {additional>0&&<Field label="Como a diferença será paga?" helper="Se ficar pendente, entra automaticamente em A receber"><Select value={additionalStatus} onChange={e=>setAdditionalStatus(e.target.value as 'Pago'|'Pendente')}><option value="Pago">Pago agora</option><option value="Pendente">Ficará pendente</option></Select></Field>}
      <Field label="Observações"><Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Motivo, condição da peça, acerto financeiro..."/></Field></aside></div>
    </Modal>
  </>;
}
